In [1]:
from sqlalchemy import create_engine
from config import password
import pymysql
pymysql.install_as_MySQLdb()
import pandas as pd

In [2]:
#Connect to local database
rds_connection_string = f"root:{password}@localhost/services_311_db"
engine = create_engine(f'mysql://{rds_connection_string}')

In [3]:
#Preview table to verify load worked
service_df = pd.read_sql_query('select * from requests_311', con=engine)

In [4]:
#checking incomplete tickets
service_df.loc[(service_df['ticket_status']!='CLOSED') & (service_df['ticket_status']!='DUP')]

,id,issue_type,case_owner,case_owner_description,street_address,city,state,zip_code,neighborhood_district,ticket_created_date_time,ticket__last_update_date_time,ticket_closed_date_time,ticket_status,location_city,latitude,longitude,method_received,goal_days,actual_completed_days
437,438,STRUCTURE MAINTENANCE - UPKEEP,Regulatory_and_Economic_Resources,Regulatory and Economic Resources,19367 SW 132ND CT,Miami_Dade_County,Florida,33177.0,District 8,2017-01-05T05:00:00.000Z,2017-04-20T04:00:00.000Z,2017-04-20T04:00:00.000Z,LIEN,MIAMI,25.586370,-80.405907,XTERFACE,180,105.0
617,618,SIGN NEW - NO PARKING / STOPPING / STANDING - ...,Public_Works_Traffic_Engineering-10-60,Public_Works_Traffic_Engineering-10-60,6320 SW 138TH CT,Miami_Dade_County,Florida,33183.0,District 1,2017-01-05T05:00:00.000Z,2018-07-19T04:00:00.000Z,None,LOCKED,MIAMI,25.707544,-80.417860,PHONE,60,NaN
621,622,SPEED HUMPS,Public_Works_Traffic_Engineering-10-60,Public_Works_Traffic_Engineering-10-60,SW 104TH AVE & SW 164TH ST,Miami_Dade_County,Florida,33157.0,District 9,2017-01-05T05:00:00.000Z,2017-01-06T05:00:00.000Z,None,LOCKED,MIAMI,25.617072,-80.361567,PHONE,60,NaN
1100,1101,ROAD CONSTRUCTION COMPLAINTS,Public_Works_Construction-6-60,Public_Works_Construction-6-60,7300 SW 42ND ST,Miami_Dade_County,Florida,33155.0,District 7,2017-01-03T05:00:00.000Z,2017-01-03T05:00:00.000Z,None,LOCKED,MIAMI,25.731382,-80.313365,PHONE,14,NaN
1248,1249,SPEED HUMPS,Public_Works_Traffic_Engineering-10-60,Public_Works_Traffic_Engineering-10-60,30657 SW 137TH AVE,Miami_Dade_County,Florida,33033.0,District 9,2017-01-03T05:00:00.000Z,2017-01-03T05:00:00.000Z,None,LOCKED,MIAMI,25.482860,-80.412058,PHONE,60,NaN
2048,2049,SETBACK VIOLATIONS,Regulatory_and_Economic_Resources,Regulatory and Economic Resources,5031 NW 198TH ST,Miami_Dade_County,Florida,33055.0,District 1,2017-01-05T05:00:00.000Z,2018-11-09T05:00:00.000Z,2017-08-15T04:00:00.000Z,LIEN,MIAMI,25.953189,-80.285251,XTERFACE,180,222.0
2081,2082,UNAUTHORIZED USE - RESIDENTIAL / BUSINESS,Regulatory_and_Economic_Resources,Regulatory and Economic Resources,5031 NW 198TH ST,Miami_Dade_County,Florida,33055.0,District 1,2017-01-05T05:00:00.000Z,2018-11-09T05:00:00.000Z,2017-08-16T04:00:00.000Z,LIEN,MIAMI,25.953189,-80.285251,XTERFACE,180,223.0
2950,2951,UNAUTHORIZED USE - RESIDENTIAL / BUSINESS,Regulatory_and_Economic_Resources,Regulatory and Economic Resources,None,None,None,NaN,District 9,2017-01-06T05:00:00.000Z,2019-03-25T04:00:00.000Z,None,LOCKED,MIAMI,25.619089,-80.477142,XTERFACE,180,NaN
2952,2953,SPEED HUMPS,Public_Works_Traffic_Engineering-10-60,Public_Works_Traffic_Engineering-10-60,20562 SW 324TH ST,Miami_Dade_County,Florida,33030.0,District 9,2017-01-06T05:00:00.000Z,2017-01-06T05:00:00.000Z,None,LOCKED,MIAMI,25.465667,-80.524757,EMAIL,60,NaN
2958,2959,SIGN NEW - NO PARKING / STOPPING / STANDING - ...,Public_Works_Traffic_Engineering-10-60,Public_Works_Traffic_Engineering-10-60,15200 SW 80TH ST,Miami_Dade_County,Florida,33193.0,District 1,2017-01-06T05:00:00.000Z,2018-10-30T04:00:00.000Z,None,LOCKED,MIAMI,25.692384,-80.439146,PHONE,60,NaN
3248,3249,STRUCTURE MAINTENANCE - UPKEEP,Regulatory_and_Economic_Resources,Regulatory and Economic Resources,7360 SW 39TH TER,Miami_Dade_County,Florida,33155.0,District 6,2017-01-04T05:00:00.000Z,2019-01-17T05:00:00.000Z,2017-05-01T04:00:00.000Z,LIEN,MIAMI,25.733599,-80.314275,XTERFACE,180,117.0
3313,3314,STRUCTURE MAINTENANCE - UPKEEP,Regulatory_and_Economic_Resources,Regulatory and Economic Resources,7360 SW 39TH TER,Miami_Dade_County,Florida,33155.0,District 6,2017-01-04T05:00:00.000Z,2019-01-17T05:00:00.000Z,2017-05-01T04:00:00.000Z,LIEN,MIAMI,25.733599,-80.314275,XTERFACE,180,117.0
3318,3319,STRUCTURE MAINTENANCE - UPKEEP,Regulatory_and_Economic_Resources,Regulatory and Economic Resources,7360 SW 39TH TER,Miami_Dade_County,Florida,33155.0,District 6,2017-01-04T05:00:00.000Z,2019-01-17T05:00:00.000Z,2017-05-01T04:00:00.000Z,LIEN,MIAMI,25.733599,-80.314275,XTERFACE,180,117.0
3413,3414,SPEED HUMPS,Public_Works_Traffic_Engineering-10-60,Public_Works_Traffic_Engineering-10-60,21600 SW 120TH AVE,Miami_Dade_County,Florida,33170.0,District 9,2017-01-04T05:00:00.000Z,2017-01-05T05:00:00.000Z,None,LOCKED,MIAMI,25.566189,-80.386708,PHONE,60,NaN
3422,3423,PAVEMENT MARKING - NEW,Public_Works_Traffic_Engineering-10-60,Public_Works_Traffic_Engineering-10-60,E 65TH ST & PALM AVE,Miami_Dade_County,Florida,33013.0,District 1,2017-01-04T05:00:00.000Z,2017-02-08T05:00:00.000Z,None,LOCKED,MIAMI,25.881424,-80.283551,EMAIL,30,NaN
3423,3424,TRAFFIC STUDY - MISCELLANEOUS - IN PUBLIC ROW,Public_Works_Traffic_Engineering-10-60,Public_Works_Traffic_Engineering-10-60,SW 167TH ST & SW 152ND AVE,Miami_Dade_County,Florida,33187.0,District 9,2017-01-04T05:00:00.000Z,2018-03-21T04:00:00.000Z,None,LOCKED,MIAMI,25.612072,-80.438219,PHONE,90,NaN
3426,3427,SIGN NEW - 4-WAY STOP,Public_Works_Traffic_Engineering-10-60,Public_Works_Traffic_Engineering-10-60,12400 SW 188TH TER,Miami_Dade_County,Florida,33177.0,District 9,2017-01-04T05:00:00.000Z,2017-01-04T05:00:00.000Z,None,LOCKED,MIAMI,25.591968,-80.393249,IPHONE,60,NaN
3427,3428,SIGN NEW - ONE WAY / DO NOT ENTER - ON PUBLIC ...,Public_Works_Traffic_Engineering-10-60,Public_Works_Traffic_Engineering-10-60,7101 RUE VENDOME,City_of_Miami_Beach,Florida,33141.0,District 4,2017-01-04T05:00:00.000Z,2017-01-04T05:00:00.000Z,None,LOCKED,MIAMI,25.855359,-80.128738,WEB,60,NaN
3782,3783,UNAUTHORIZED USE - RESIDENTIAL / BUSINESS,Regulatory_and_Economic_Resources,Regulatory and Economic Resources,2542 NE 182ND ST,Miami_Dade_County,Florida,33160.0,District 4,2017-01-04T05:00:00.000Z,2019-04-29T04:00:00.000Z,2017-06-27T04:00:00.000Z,LIEN,MIAMI,25.943386,-80.150132,XTERFACE,180,174.0
4030,4031,UNAUTHORIZED USE - RESIDENTIAL / BUSINESS,Regulatory_and_Economic_Resources,Regulatory and Economic Resources,11624 NW 13TH AVE,Miami_Dade_County,Florida,33167.0,District 2,2017-01-06T05:00:00.000Z,2019-05-03T04:00:00.000Z,2017-05-19T04:00:00.000Z,LIEN,MIAMI,25.880906,-80.220741,XTERFACE,180,133.0
4224,4225,ROAD SURFACE DEFECT,Public_Works_Road_And_Bridges-16-60,Public_Works_Road_And_Bridges-16-60,10853 SW 344TH ST,Miami_Dade_County,Florida,33035.0,District 9,2017-01-06T05:00:00.000Z,2017-01-06T05:00:00.000Z,None,LOCKED,MIAMI,25.448102,-80.365178,IPHONE,10,NaN
4244,4245,TRAFFIC SIGNAL PED LIGHT OR BUTTON INOPERATIVE,Public_Works_traffic_Signals_And_Signs-15-60,Public_Works_traffic_Signals_And_Signs-15-60,12300 NE 14TH AVE,City_of_North_Miami,Florida,33161.0,District 4,2017-01-06T05:00:00.000Z,2017-01-09T05:00:00.000Z,None,LOCKED,MIAMI,25.889093,-80.170307,PHONE,15,NaN
4379,4380,POTHOLE,Public_Works_Road_And_Bridges-16-60,Public_Works_Road_And_Bridges-16-60,3208 SW 142ND CT,Miami_Dade_County,Florida,33175.0,District 1,2017-01-06T05:00:00.000Z,2017-01-06T05:00:00.000Z,None,LOCKED,MIAMI,25.737470,-80.425049,WALKIN,3,NaN
4438,4439,STREET LIGHT - ALL PROBLEMS,Public_Works_traffic_Signals_And_Signs-15-60,Public_Works_traffic_Signals_And_Signs-15-60,1831 SW 27TH AVE,City_of_Miami,Florida,33145.0,District 5,2017-01-06T05:00:00.000Z,2017-01-06T05:00:00.000Z,None,LOCKED,MIAMI,25.754487,-80.238100,PHONE,3,NaN
4468,4469,TRAFFIC SIGNAL BULB BURNED OUT,Public_Works_traffic_Signals_And_Signs-15-60,Public_Works_traffic_Signals_And_Signs-15-60,SW 42ND AVE & US 1 HWY,City_of_Coral_Gables,Florida,33146.0,District 7,2017-01-06T05:00:00.000Z,2017-01-06T05:00:00.000Z,None,LOCKED,MIAMI,25.726526,-80.261687,PHONE,10,NaN
4853,4854,SIGN NEW - STOP / YIELD - ON PUBLIC STREET,Public_Works_Traffic_Engineering-10-60,Public_Works_Traffic_Engineering-10-60,9300 S DADELAND BLVD,Miami_Dade_County,Florida,33156.0,District 7,2017-01-09T05:00:00.000Z,2017-01-09T05:00:00.000Z,None,LOCKED,MIAMI,25.683537,-80.316442,PHONE,60,NaN
4863,4864,SPEED HUMPS,Public_Works_Traffic_Engineering-10-60,Public_Works_Traffic_Engineering-10-60,18300 SW 154TH PL,Miami_Dade_County,Florida,33187.0,District 9,2017-01-09T05:00:00.000Z,2017-01-10T05:00:00.000Z,None,LOCKED,MIAMI,25.596666,-80.443602,PHONE,60,NaN
4892,4893,ROAD CONSTRUCTION COMPLAINTS,Public_Works_Construction-6-60,Public_Works_Construction-6-60,17800 NW 52ND AVE,Miami_Dade_County,Florida,33055.0,District 1,2017-01-07T05:00:00.000Z,2017-01-09T05:00:00.000Z,None,LOCKED,MIAMI,25.934760,-80.285523,PHONE,14,NaN
5040,5041,FAILURE TO OBTAIN ZONING PERMIT,Regulatory_and_Economic_Resources,Regulatory and Economic Resources,12906 SW 46TH LN,Miami_Dade_County,Florida,33175.0,District 1,2017-01-09T05:00:00.000Z,2017-01-20T05:00:00.000Z,None,LOCKED,MIAMI,25.722310,-80.404032,PHONE,180,NaN
5197,5198,SIGN NEW - 4-WAY STOP,Public_Works_Traffic_Engineering-10-60,Public_Works_Traffic_Engineering-10-60,15900 NW 38TH PL,City_of_Miami_Gardens,Florida,33054.0,District 1,2017-01-10T05:00:00.000Z,2017-01-10T05:00:00.000Z,None,LOCKED,MIAMI,25.918931,-80.263898,PHONE,60,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3561290,3561291,SIGN NEW - 4-WAY STOP,Public_Works_Traffic_Engineering-10-60,Public_Works_Traffic_Engineering-10-60,ABBOTT AVE & 78TH ST,City_of_Miami_Beach,Florida,33141.0,District 4,2017-11-30T05:00:00.000Z,2017-12-01T05:00:00.000Z,None,LOCKED,MIAMI,25.863122,-80.123010,PHONE,60,NaN
3561291,3561292,SIGN NEW - STOP / YIELD - ON PUBLIC STREET,Public_Works_Traffic_Engineering-10-60,Public_Works_Traffic_Engineering-10-60,1510 NE 14TH ST,Miami_Dade_County,Florida,33033.0,District 8,2017-11-30T05:00:00.000Z,2017-12-01T05:00:00.000Z,None,LOCKED,MIAMI,25.483478,-80.456726,PHONE,60,NaN
3561292,3561293,SPEED HUMPS,Public_Works_Traffic_Engineering-10-60,Public_Works_Traffic_Engineering-10-60,8051 SW 188TH ST,Town_of_Cutler_Bay,Florida,33157.0,District 8,2017-11-30T05:00:00.000Z,2017-11-30T05:00:00.000Z,None,LOCKED,MIAMI,25.592716,-80.322385,PHONE,60,NaN
3561294,3561295,TRAFFIC SIGN PAVEMENT MARKINGS FADED,Public_Works_Traffic_Engineering-10-60,Public_Works_Traffic_Engineering-10-60,7000 SW 80TH CT,Miami_Dade_County,Florida,33143.0,District 7,2017-11-30T05:00:00.000Z,2018-06-28T04:00:00.000Z,None,LOCKED,MIAMI,25.704402,-80.324830,EMAIL,120,NaN
3561296,3561297,CANAL - BANK TREES NEED CUTTING,Public_Works_Road_And_Bridges-16-60,Public_Works_Road_And_Bridges-16-60,10830 SW 67TH DR,Miami_Dade_County,Florida,33173.0,District 1,2017-11-29T05:00:00.000Z,2017-11-29T05:00:00.000Z,None,LOCKED,MIAMI,25.706543,-80.369922,PHONE,180,NaN
3561351,3561352,STREET LIGHT - ALL PROBLEMS,Public_Works_traffic_Signals_And_Signs-15-60,Public_Works_traffic_Signals_And_Signs-15-60,8325 S DIXIE HWY,Miami_Dade_County,Florida,33143.0,District 7,2017-11-29T05:00:00.000Z,2017-11-29T05:00:00.000Z,None,LOCKED,MIAMI,25.692612,-80.301953,PHONE,3,NaN
3561488,3561489,STREET LIGHT - ALL PROBLEMS,Public_Works_traffic_Signals_And_Signs-15-60,Public_Works_traffic_Signals_And_Signs-15-60,SW 8TH AVE & SW 1ST ST,City_of_Miami,Florida,33130.0,District 5,2017-11-30T05:00:00.000Z,2017-11-30T05:00:00.000Z,None,LOCKED,MIAMI,25.772730,-80.207685,PHONE,3,NaN
3561490,3561491,STREET LIGHT - ALL PROBLEMS,Public_Works_traffic_Signals_And_Signs-15-60,Public_Works_traffic_Signals_And_Signs-15-60,1700 NW 1ST ST,City_of_Miami,Florida,33125.0,District 5,2017-11-30T05:00:00.000Z,2017-12-09T05:00:00.000Z,None,LOCKED,MIAMI,25.774410,-80.223170,PHONE,3,NaN
3561519,3561520,TRAFFIC SIGNAL COMPLETELY OUT,Public_Works_traffic_Signals_And_Signs-15-60,Public_Works_traffic_Signals_And_Signs-15-60,77TH ST & DICKENS AVE,City_of_Miami_Beach,Florida,33141.0,District 4,2017-11-30T05:00:00.000Z,2017-11-30T05:00:00.000Z,None,LOCKED,MIAMI,25.862058,-80.125507,PHONE,0,NaN
3561625,3561626,BULKY TRASH REQUEST,Solid_Waste_Management,Solid Waste Management,18015 NW 62ND CT,Miami_Dade_County,Florida,33015.0,District 1,2017-11-30T05:00:00.000Z,2017-12-13T05:00:00.000Z,2017-12-13T05:00:00.000Z,CANCEL,MIAMI,25.937735,-80.302866,WEB,8,13.0
3561655,3561656,BULKY TRASH REQUEST,Solid_Waste_Management,Solid Waste Management,5835 SW 108TH PL,Miami_Dade_County,Florida,33173.0,District 1,2017-11-30T05:00:00.000Z,2017-12-13T05:00:00.000Z,2017-12-13T05:00:00.000Z,CANCEL,MIAMI,25.712838,-80.369954,WEB,8,13.0
3561922,3561923,FAILURE TO OBTAIN ZONING PERMIT,Regulatory_and_Economic_Resources,Regulatory and Economic Resources,22300 SW 250TH ST,Miami_Dade_County,Florida,33031.0,District 8,2017-11-30T05:00:00.000Z,2019-02-05T05:00:00.000Z,None,LOCKED,MIAMI,25.533062,-80.553482,PHONE,180,NaN
3561931,3561932,TRAFFIC SIGNAL RED DISPLAY TOO LONG OR GREEN T...,Public_Works_traffic_Signals_And_Signs-15-60,Public_Works_traffic_Signals_And_Signs-15-60,14700 SW 264TH ST,Miami_Dade_County,Florida,33032.0,District 8,2017-11-30T05:00:00.000Z,2017-11-30T05:00:00.000Z,None,LOCKED,MIAMI,25.521571,-80.428950,PHONE,30,NaN
3562043,3562044,BULKY TRASH REQUEST,Solid_Waste_Management,Solid Waste Management,14775 SW 178TH TER,Miami_Dade_County,Florida,33187.0,District 9,2017-11-30T05:00:00.000Z,2017-12-13T05:00:00.000Z,2017-12-13T05:00:00.000Z,CANCEL,MIAMI,25.601522,-80.431306,WEB,8,13.0
3562201,3562202,FAILURE TO OBTAIN ZONING PERMIT,Regulatory_and_Economic_Resources,Regulatory and Economic Resources,4200 SW 97TH PL,Miami_Dade_County,Florida,33165.0,District 1,2017-11-30T05:00:00.000Z,2019-05-09T04:00:00.000Z,2019-05-09T04:00:00.000Z,LIEN,MIAMI,25.729172,-80.353427,XTERFACE,180,525.0
3562302,3562303,UNAUTHORIZED USE - RESIDENTIAL / BUSINESS,Regulatory_and_Economic_Resources,Regulatory and Economic Resources,14500 W DIXIE HWY,Miami_Dade_County,Florida,33161.0,District 2,2017-12-22T05:00:00.000Z,2019-05-03T04:00:00.000Z,2018-06-11T04:00:00.000Z,LIEN,MIAMI,25.909712,-80.169244,XTERFACE,180,171.0
3562405,3562406,SIDEWALK BROKEN / RAISED,Public_Works_Road_And_Bridges-16-60,Public_Works_Road_And_Bridges-16-60,14565 SW 270TH ST,Miami_Dade_County,Florida,33032.0,District 9,2017-12-22T05:00:00.000Z,2017-12-22T05:00:00.000Z,None,LOCKED,MIAMI,25.516291,-80.427795,XTERFACE,30,NaN
3562410,3562411,SIDEWALK BROKEN / RAISED,Public_Works_Road_And_Bridges-16-60,Public_Works_Road_And_Bridges-16-60,20705 NE 9TH CT,Miami_Dade_County,Florida,33179.0,District 1,2017-12-22T05:00:00.000Z,2017-12-22T05:00:00.000Z,None,LOCKED,MIAMI,25.966593,-80.183401,XTERFACE,30,NaN
3562526,3562527,STRUCTURE MAINTENANCE - UPKEEP,Regulatory_and_Economic_Resources,Regulatory and Economic Resources,3450 NW 96TH ST,Miami_Dade_County,Florida,33147.0,District 2,2017-12-22T05:00:00.000Z,2018-11-09T05:00:00.000Z,2018-06-20T04:00:00.000Z,LIEN,MIAMI,25.861563,-80.254542,XTERFACE,180,180.0
3562578,3562579,BULKY TRASH REQUEST,Solid_Waste_Management,Solid Waste Management,9635 SW 121ST ST,Miami_Dade_County,Florida,33176.0,District 8,2017-12-22T05:00:00.000Z,2018-01-03T05:00:00.000Z,2018-01-03T05:00:00.000Z,CANCEL,MIAMI,25.657477,-80.349916,WEB,8,12.0
3562609,3562610,CAT TRAP REQUEST,Enforcement_Section-3-36,Enforcement_Section-3-36,7204 SW 128TH CT,Miami_Dade_County,Florida,33183.0,District 1,2017-12-22T05:00:00.000Z,2017-12-29T05:00:00.000Z,None,OPEN,MIAMI,25.700127,-80.401538,PHONE,180,NaN
3562657,3562658,TRAFFIC SIGNAL OUT OF SYNC WITH OTHER TRAFFIC ...,Public_Works_traffic_Signals_And_Signs-15-60,Public_Works_traffic_Signals_And_Signs-15-60,SW 8TH AVE & W FLAGLER ST,City_of_Miami,Florida,33130.0,District 5,2017-12-22T05:00:00.000Z,2017-12-22T05:00:00.000Z,None,LOCKED,MIAMI,25.773719,-80.207723,EMAIL,30,NaN
3562799,3562800,STRAY / DOG-AT-LARGE,Enforcement_Section-3-36,Enforcement_Section-3-36,7708 NW 6TH CT,City_of_Miami,Florida,33150.0,District 3,2017-12-22T05:00:00.000Z,2017-12-29T05:00:00.000Z,2017-12-29T05:00:00.000Z,CANCEL,MIAMI,25.845506,-80.208230,PHONE,180,7.0
3562811,3562812,ILLEGAL DUMPING / LITTER,COM_Code_Enforcement,COM_Code_Enforcement,4063 HARDIE AVE,City_of_Miami,Florida,33133.0,District 7,2017-12-22T05:00:00.000Z,2017-12-22T05:00:00.000Z,None,OPEN,MIAMI,25.713059,-80.258394,WEB,7,NaN
3562883,3562884,BULKY TRASH REQUEST,Solid_Waste_Management,Solid Waste Management,4800 SW 93RD CT,Miami_Dade_County,Florida,33165.0,District 1,2017-12-22T05:00:00.000Z,2018-01-03T05:00:00.000Z,2018-01-03T05:00:00.000Z,CANCEL,MIAMI,25.724197,-80.346936,WEB,8,12.0
3562935,3562936,CANAL - CLEANING,Public_Works_Road_And_Bridges-16-60,Public_Works_Road_And_Bridges-16-60,SW 64TH AVE & SW 84TH ST,Miami_Dade_County,Florida,33143.0,District 7,2017-12-23T05:00:00.000Z,2017-12-23T05:00:00.000Z,None,LOCKED,MIAMI,25.692895,-80.297007,EMAIL,5,NaN
3563040,3563041,GRAFFITI ON COUNTY PROPERTY OR ROW,Public_Works_Road_And_Bridges-16-60,Public_Works_Road_And_Bridges-16-60,W DIXIE HWY & NE 189TH ST,Miami_Dade_County,Florida,33180.0,District 4,2017-12-23T05:00:00.000Z,2017-12-23T05:00:00.000Z,None,LOCKED,MIAMI,25.950254,-80.148886,EMAIL,14,NaN
3563052,3563053,POTHOLE,Public_Works_Road_And_Bridges-16-60,Public_Works_Road_And_Bridges-16-60,11960 SW 144TH ST,Miami_Dade_County,Florida,33186.0,District 9,2017-12-22T05:00:00.000Z,2017-12-22T05:00:00.000Z,None,LOCKED,MIAMI,25.633985,-80.388138,WEB,3,NaN
3563393,3563394,TRAFFIC SIGNAL OUT OF SYNC WITH OTHER TRAFFIC ...,Public_Works_traffic_Signals_And_Signs-15-60,Public_Works_traffic_Signals_And_Signs-15-60,3600 NE 2ND AVE,City_of_Miami,Florida,33137.0,District 3,2017-12-29T05:00:00.000Z,2017-12-29T05:00:00.000Z,None,LOCKED,MIAMI,25.810799,-80.191526,PHONE,30,NaN
3563892,3563893,TRAFFIC SIGN CONTROL SIGNS DOWN DAMAGED MIS...,Public_Works_Traffic_Engineering-10-60,Public_Works_Traffic_Engineering-10-60,NW 3RD AVE & NW 150TH ST,Miami_Dade_County,Florida,33168.0,District 2,2017-12-30T05:00:00.000Z,2017-12-30T05:00:00.000Z,None,LOCKED,MIAMI,25.912353,-80.205635,PHONE,2,NaN

In [5]:
#find completed tickets and non negative completed days
service_closed = service_df.loc[(service_df['ticket_status'] == 'CLOSED') & (service_df['actual_completed_days'] >= 0)]
service_closed.head()

,id,issue_type,case_owner,case_owner_description,street_address,city,state,zip_code,neighborhood_district,ticket_created_date_time,ticket__last_update_date_time,ticket_closed_date_time,ticket_status,location_city,latitude,longitude,method_received,goal_days,actual_completed_days
0,1,BULKY TRASH REQUEST,Solid_Waste_Management,Solid Waste Management,10245 SW 37TH TER,Miami_Dade_County,Florida,33165.0,District 1,2017-01-04T05:00:00.000Z,2017-01-13T05:00:00.000Z,2017-01-13T05:00:00.000Z,CLOSED,MIAMI,25.734851,-80.360870,PHONE,8,9.0
1,2,RECYCLING BLUE CART ISSUES,Solid_Waste_Management,Solid Waste Management,15445 SW 114TH ST,Miami_Dade_County,Florida,33196.0,District 1,2017-01-04T05:00:00.000Z,2017-01-11T05:00:00.000Z,2017-01-11T05:00:00.000Z,CLOSED,MIAMI,25.660831,-80.445467,PHONE,10,7.0
2,3,GREEN WASTE CART REQUEST,Solid_Waste_Management,Solid Waste Management,14341 SW 151ST CT,Miami_Dade_County,Florida,33196.0,District 1,2017-01-04T05:00:00.000Z,2017-01-11T05:00:00.000Z,2017-01-11T05:00:00.000Z,CLOSED,MIAMI,25.633522,-80.438608,PHONE,10,7.0
3,4,GREEN WASTE CART REQUEST,Solid_Waste_Management,Solid Waste Management,12850 NW 8TH ST,Miami_Dade_County,Florida,33182.0,District 1,2017-01-04T05:00:00.000Z,2017-01-12T05:00:00.000Z,2017-01-12T05:00:00.000Z,CLOSED,MIAMI,25.776314,-80.404338,PHONE,10,8.0
4,5,GARBAGE COMPLAINT,Solid_Waste_Management,Solid Waste Management,3265 NW 46TH ST,Miami_Dade_County,Florida,33142.0,District 3,2017-01-04T05:00:00.000Z,2017-01-06T05:00:00.000Z,2017-01-06T05:00:00.000Z,CLOSED,MIAMI,25.816450,-80.249984,PHONE,5,2.0

In [6]:
service_drop =service_closed[['issue_type', 'case_owner','city','location_city','actual_completed_days']]
service_drop.head()

,issue_type,case_owner,city,location_city,actual_completed_days
0,BULKY TRASH REQUEST,Solid_Waste_Management,Miami_Dade_County,MIAMI,9.0
1,RECYCLING BLUE CART ISSUES,Solid_Waste_Management,Miami_Dade_County,MIAMI,7.0
2,GREEN WASTE CART REQUEST,Solid_Waste_Management,Miami_Dade_County,MIAMI,7.0
3,GREEN WASTE CART REQUEST,Solid_Waste_Management,Miami_Dade_County,MIAMI,8.0
4,GARBAGE COMPLAINT,Solid_Waste_Management,Miami_Dade_County,MIAMI,2.0

In [7]:
city_group = service_drop.groupby(['city', 'case_owner','issue_type'])
df_calc = city_group.describe()
#df_calc.head()
df_reset = df_calc.reset_index()

In [8]:
df_reset.head()

                  city                case_owner                   issue_type  \

0  Bal_Harbour_Village        Citations_and_Tags      ANIMAL SERVICES DOG TAG
1  Bal_Harbour_Village        Citations_and_Tags           PET ACCOUNT UPDATE
2  Bal_Harbour_Village  Enforcement_Section-3-36  DANGEROUS DOG INVESTIGATION
3  Bal_Harbour_Village  Enforcement_Section-3-36        DEAD ANIMAL PICKUP MD
4  Bal_Harbour_Village  Enforcement_Section-3-36               INJURED ANIMAL

  actual_completed_days
                  count       mean       std   min   25%   50%   75%   max
0                  22.0   0.000000  0.000000   0.0   0.0   0.0   0.0   0.0
1                  77.0   1.571429  0.909433   1.0   1.0   1.0   3.0   3.0
2                  11.0  36.000000  0.000000  36.0  36.0  36.0  36.0  36.0
3                  11.0   0.000000  0.000000   0.0   0.0   0.0   0.0   0.0
4                  11.0   0.000000  0.000000   0.0   0.0   0.0   0.0   0.0

In [9]:
#Drop multilevel index 
df_reset.columns = df_reset.columns.droplevel()
#new_index
#df_reset.columns.droplevel(1)
df_reset.head()

,,,,count,mean,std,min,25%,50%,75%,max
0,Bal_Harbour_Village,Citations_and_Tags,ANIMAL SERVICES DOG TAG,22.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0
1,Bal_Harbour_Village,Citations_and_Tags,PET ACCOUNT UPDATE,77.0,1.571429,0.909433,1.0,1.0,1.0,3.0,3.0
2,Bal_Harbour_Village,Enforcement_Section-3-36,DANGEROUS DOG INVESTIGATION,11.0,36.000000,0.000000,36.0,36.0,36.0,36.0,36.0
3,Bal_Harbour_Village,Enforcement_Section-3-36,DEAD ANIMAL PICKUP MD,11.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0
4,Bal_Harbour_Village,Enforcement_Section-3-36,INJURED ANIMAL,11.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0

In [10]:
#rename columns
df_reset.columns = ['city', 'case_owner', 'issue_type', 'count', 'mean', 'std', 'min', '25%', '50%', '75%', 'max']
df_reset.head()

,city,case_owner,issue_type,count,mean,std,min,25%,50%,75%,max
0,Bal_Harbour_Village,Citations_and_Tags,ANIMAL SERVICES DOG TAG,22.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0
1,Bal_Harbour_Village,Citations_and_Tags,PET ACCOUNT UPDATE,77.0,1.571429,0.909433,1.0,1.0,1.0,3.0,3.0
2,Bal_Harbour_Village,Enforcement_Section-3-36,DANGEROUS DOG INVESTIGATION,11.0,36.000000,0.000000,36.0,36.0,36.0,36.0,36.0
3,Bal_Harbour_Village,Enforcement_Section-3-36,DEAD ANIMAL PICKUP MD,11.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0
4,Bal_Harbour_Village,Enforcement_Section-3-36,INJURED ANIMAL,11.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0

In [11]:
df_drop = df_reset[['city', 'case_owner', 'issue_type', 'mean']]
city_df = df_drop.dropna()
city_df.head()
#city_df.isna().any()

,city,case_owner,issue_type,mean
0,Bal_Harbour_Village,Citations_and_Tags,ANIMAL SERVICES DOG TAG,0.000000
1,Bal_Harbour_Village,Citations_and_Tags,PET ACCOUNT UPDATE,1.571429
2,Bal_Harbour_Village,Enforcement_Section-3-36,DANGEROUS DOG INVESTIGATION,36.000000
3,Bal_Harbour_Village,Enforcement_Section-3-36,DEAD ANIMAL PICKUP MD,0.000000
4,Bal_Harbour_Village,Enforcement_Section-3-36,INJURED ANIMAL,0.000000

In [12]:
# city_df.to_sql(name='requests_calc', con=engine, if_exists='replace', index=False)

In [13]:
#check table
# new_df = pd.read_sql_query('select * from requests_calc', con=engine)
# new_df.head()

In [14]:
#service_drop.loc[(service_drop['issue_type'] == 'DANGEROUS DOG INVESTIGATION') & (service_drop['city'] == 'Bal_Harbour_Village')]

In [15]:
#owner_group = service_df.groupby(['city', 'case_owner'])
#owner_group.describe()

In [16]:
total_group = service_drop.groupby(['location_city', 'case_owner', 'issue_type'])

In [17]:
#remove NaNs
total_calc = total_group.describe()
#total_calc = total_calc.dropna()

In [18]:
total_calc.head()

                                                            actual_completed_days  \
                                                                            count
location_city case_owner           issue_type
MIAMI         COM_Code_Enforcement ILLEGAL DUMPING / LITTER               25883.0
              Citations_and_Tags   ANIMAL SERVICES DOG TAG                 9856.0
                                   FOUND PET                                506.0
                                   LOST PET                                9075.0
                                   PET ACCOUNT UPDATE                    102652.0

                                                                        \
                                                                  mean
location_city case_owner           issue_type
MIAMI         COM_Code_Enforcement ILLEGAL DUMPING / LITTER  28.424989
              Citations_and_Tags   ANIMAL SERVICES DOG TAG    0.004464
                                   FOUND PET                 10.347826
                                   LOST PET                   4.403636
                                   PET ACCOUNT UPDATE         1.501179

                                                                             \
                                                                   std  min
location_city case_owner           issue_type
MIAMI         COM_Code_Enforcement ILLEGAL DUMPING / LITTER  56.701841  0.0
              Citations_and_Tags   ANIMAL SERVICES DOG TAG    0.133563  0.0
                                   FOUND PET                 15.342350  0.0
                                   LOST PET                   4.845832  0.0
                                   PET ACCOUNT UPDATE         2.706251  0.0

                                                                             \
                                                             25%  50%   75%
location_city case_owner           issue_type
MIAMI         COM_Code_Enforcement ILLEGAL DUMPING / LITTER  4.0  9.0  32.0
              Citations_and_Tags   ANIMAL SERVICES DOG TAG   0.0  0.0   0.0
                                   FOUND PET                 1.0  3.0  11.0
                                   LOST PET                  1.0  3.0   6.0
                                   PET ACCOUNT UPDATE        1.0  1.0   1.0


                                                               max
location_city case_owner           issue_type
MIAMI         COM_Code_Enforcement ILLEGAL DUMPING / LITTER  373.0
              Citations_and_Tags   ANIMAL SERVICES DOG TAG     4.0
                                   FOUND PET                  56.0
                                   LOST PET                   64.0
                                   PET ACCOUNT UPDATE         76.0

In [19]:
#adjust and drop columns names
total_calc_clean = total_calc.reset_index()
total_calc_clean.columns = total_calc_clean.columns.droplevel()

In [20]:
#preview
total_calc_clean.head()

,,,,count,mean,std,min,25%,50%,75%,max
0,MIAMI,COM_Code_Enforcement,ILLEGAL DUMPING / LITTER,25883.0,28.424989,56.701841,0.0,4.0,9.0,32.0,373.0
1,MIAMI,Citations_and_Tags,ANIMAL SERVICES DOG TAG,9856.0,0.004464,0.133563,0.0,0.0,0.0,0.0,4.0
2,MIAMI,Citations_and_Tags,FOUND PET,506.0,10.347826,15.342350,0.0,1.0,3.0,11.0,56.0
3,MIAMI,Citations_and_Tags,LOST PET,9075.0,4.403636,4.845832,0.0,1.0,3.0,6.0,64.0
4,MIAMI,Citations_and_Tags,PET ACCOUNT UPDATE,102652.0,1.501179,2.706251,0.0,1.0,1.0,1.0,76.0

In [21]:
#rename columns
total_calc_clean.columns = ['location_city', 'case_owner', 'issue_type', 'count', 'mean', 'std', 'min', '25%', '50%', '75%', 'max']
total_calc_clean.head()

,location_city,case_owner,issue_type,count,mean,std,min,25%,50%,75%,max
0,MIAMI,COM_Code_Enforcement,ILLEGAL DUMPING / LITTER,25883.0,28.424989,56.701841,0.0,4.0,9.0,32.0,373.0
1,MIAMI,Citations_and_Tags,ANIMAL SERVICES DOG TAG,9856.0,0.004464,0.133563,0.0,0.0,0.0,0.0,4.0
2,MIAMI,Citations_and_Tags,FOUND PET,506.0,10.347826,15.342350,0.0,1.0,3.0,11.0,56.0
3,MIAMI,Citations_and_Tags,LOST PET,9075.0,4.403636,4.845832,0.0,1.0,3.0,6.0,64.0
4,MIAMI,Citations_and_Tags,PET ACCOUNT UPDATE,102652.0,1.501179,2.706251,0.0,1.0,1.0,1.0,76.0

In [22]:
#check for na
total_calc_clean.isna().any()

location_city    False
case_owner       False
issue_type       False
count            False
mean             False
std              False
min              False
25%              False
50%              False
75%              False
max              False
dtype: bool

In [23]:
#remove NA

In [24]:
#Average completed days for all of miami dade county
total_avg = total_calc_clean[['case_owner', 'issue_type','mean']]
total_avg_rename = total_avg.rename(columns= {'mean':'total_mean'})
total_avg_rename.head()

             case_owner                issue_type  total_mean
0  COM_Code_Enforcement  ILLEGAL DUMPING / LITTER   28.424989
1    Citations_and_Tags   ANIMAL SERVICES DOG TAG    0.004464
2    Citations_and_Tags                 FOUND PET   10.347826
3    Citations_and_Tags                  LOST PET    4.403636
4    Citations_and_Tags        PET ACCOUNT UPDATE    1.501179

In [25]:
#check for na
total_avg.isna().any()

case_owner    False
issue_type    False
mean          False
dtype: bool

In [26]:
city_avg = city_df[['city','case_owner', 'issue_type','mean']]
city_avg.head()

,city,case_owner,issue_type,mean
0,Bal_Harbour_Village,Citations_and_Tags,ANIMAL SERVICES DOG TAG,0.000000
1,Bal_Harbour_Village,Citations_and_Tags,PET ACCOUNT UPDATE,1.571429
2,Bal_Harbour_Village,Enforcement_Section-3-36,DANGEROUS DOG INVESTIGATION,36.000000
3,Bal_Harbour_Village,Enforcement_Section-3-36,DEAD ANIMAL PICKUP MD,0.000000
4,Bal_Harbour_Village,Enforcement_Section-3-36,INJURED ANIMAL,0.000000

In [27]:
#Check location for this issue type
city_df.loc[city_df['issue_type'] == 'ILLEGAL EXCAVATION']

,city,case_owner,issue_type,mean
1385,Miami_Dade_County,Regulatory_and_Economic_Resources,ILLEGAL EXCAVATION,68.8

In [28]:
#check location for this issue type
total_calc_clean.loc[total_calc_clean['issue_type'] == 'ILLEGAL EXCAVATION']

,location_city,case_owner,issue_type,count,mean,std,min,25%,50%,75%,max
140,MIAMI,Regulatory_and_Economic_Resources,ILLEGAL EXCAVATION,110.0,68.8,152.957678,0.0,6.0,8.0,40.0,520.0

In [29]:
service_df.loc[(service_df['issue_type']=='ANIMAL SERVICES DOG TAG') & (service_df['city']=='Bal_Harbour_Village')]

,id,issue_type,case_owner,case_owner_description,street_address,city,state,zip_code,neighborhood_district,ticket_created_date_time,ticket__last_update_date_time,ticket_closed_date_time,ticket_status,location_city,latitude,longitude,method_received,goal_days,actual_completed_days
128893,128894,ANIMAL SERVICES DOG TAG,Citations_and_Tags,Citations_and_Tags,10240 COLLINS AVE,Bal_Harbour_Village,Florida,33154.0,District 4,2017-05-23T04:00:00.000Z,2017-05-23T04:00:00.000Z,2017-05-23T04:00:00.000Z,CLOSED,MIAMI,25.896969,-80.125006,WALKIN,0,0.0
312437,312438,ANIMAL SERVICES DOG TAG,Citations_and_Tags,Citations_and_Tags,10240 COLLINS AVE,Bal_Harbour_Village,Florida,33154.0,District 4,2017-12-15T05:00:00.000Z,2017-12-15T05:00:00.000Z,2017-12-15T05:00:00.000Z,CLOSED,MIAMI,25.896969,-80.125006,WALKIN,0,0.0
452913,452914,ANIMAL SERVICES DOG TAG,Citations_and_Tags,Citations_and_Tags,10240 COLLINS AVE,Bal_Harbour_Village,Florida,33154.0,District 4,2017-05-23T04:00:00.000Z,2017-05-23T04:00:00.000Z,2017-05-23T04:00:00.000Z,CLOSED,MIAMI,25.896969,-80.125006,WALKIN,0,0.0
636457,636458,ANIMAL SERVICES DOG TAG,Citations_and_Tags,Citations_and_Tags,10240 COLLINS AVE,Bal_Harbour_Village,Florida,33154.0,District 4,2017-12-15T05:00:00.000Z,2017-12-15T05:00:00.000Z,2017-12-15T05:00:00.000Z,CLOSED,MIAMI,25.896969,-80.125006,WALKIN,0,0.0
776933,776934,ANIMAL SERVICES DOG TAG,Citations_and_Tags,Citations_and_Tags,10240 COLLINS AVE,Bal_Harbour_Village,Florida,33154.0,District 4,2017-05-23T04:00:00.000Z,2017-05-23T04:00:00.000Z,2017-05-23T04:00:00.000Z,CLOSED,MIAMI,25.896969,-80.125006,WALKIN,0,0.0
960477,960478,ANIMAL SERVICES DOG TAG,Citations_and_Tags,Citations_and_Tags,10240 COLLINS AVE,Bal_Harbour_Village,Florida,33154.0,District 4,2017-12-15T05:00:00.000Z,2017-12-15T05:00:00.000Z,2017-12-15T05:00:00.000Z,CLOSED,MIAMI,25.896969,-80.125006,WALKIN,0,0.0
1100953,1100954,ANIMAL SERVICES DOG TAG,Citations_and_Tags,Citations_and_Tags,10240 COLLINS AVE,Bal_Harbour_Village,Florida,33154.0,District 4,2017-05-23T04:00:00.000Z,2017-05-23T04:00:00.000Z,2017-05-23T04:00:00.000Z,CLOSED,MIAMI,25.896969,-80.125006,WALKIN,0,0.0
1284497,1284498,ANIMAL SERVICES DOG TAG,Citations_and_Tags,Citations_and_Tags,10240 COLLINS AVE,Bal_Harbour_Village,Florida,33154.0,District 4,2017-12-15T05:00:00.000Z,2017-12-15T05:00:00.000Z,2017-12-15T05:00:00.000Z,CLOSED,MIAMI,25.896969,-80.125006,WALKIN,0,0.0
1424973,1424974,ANIMAL SERVICES DOG TAG,Citations_and_Tags,Citations_and_Tags,10240 COLLINS AVE,Bal_Harbour_Village,Florida,33154.0,District 4,2017-05-23T04:00:00.000Z,2017-05-23T04:00:00.000Z,2017-05-23T04:00:00.000Z,CLOSED,MIAMI,25.896969,-80.125006,WALKIN,0,0.0
1608517,1608518,ANIMAL SERVICES DOG TAG,Citations_and_Tags,Citations_and_Tags,10240 COLLINS AVE,Bal_Harbour_Village,Florida,33154.0,District 4,2017-12-15T05:00:00.000Z,2017-12-15T05:00:00.000Z,2017-12-15T05:00:00.000Z,CLOSED,MIAMI,25.896969,-80.125006,WALKIN,0,0.0
1748993,1748994,ANIMAL SERVICES DOG TAG,Citations_and_Tags,Citations_and_Tags,10240 COLLINS AVE,Bal_Harbour_Village,Florida,33154.0,District 4,2017-05-23T04:00:00.000Z,2017-05-23T04:00:00.000Z,2017-05-23T04:00:00.000Z,CLOSED,MIAMI,25.896969,-80.125006,WALKIN,0,0.0
1932537,1932538,ANIMAL SERVICES DOG TAG,Citations_and_Tags,Citations_and_Tags,10240 COLLINS AVE,Bal_Harbour_Village,Florida,33154.0,District 4,2017-12-15T05:00:00.000Z,2017-12-15T05:00:00.000Z,2017-12-15T05:00:00.000Z,CLOSED,MIAMI,25.896969,-80.125006,WALKIN,0,0.0
2073013,2073014,ANIMAL SERVICES DOG TAG,Citations_and_Tags,Citations_and_Tags,10240 COLLINS AVE,Bal_Harbour_Village,Florida,33154.0,District 4,2017-05-23T04:00:00.000Z,2017-05-23T04:00:00.000Z,2017-05-23T04:00:00.000Z,CLOSED,MIAMI,25.896969,-80.125006,WALKIN,0,0.0
2256557,2256558,ANIMAL SERVICES DOG TAG,Citations_and_Tags,Citations_and_Tags,10240 COLLINS AVE,Bal_Harbour_Village,Florida,33154.0,District 4,2017-12-15T05:00:00.000Z,2017-12-15T05:00:00.000Z,2017-12-15T05:00:00.000Z,CLOSED,MIAMI,25.896969,-80.125006,WALKIN,0,0.0
2397033,2397034,ANIMAL SERVICES DOG TAG,Citations_and_Tags,Citations_and_Tags,10240 COLLINS AVE,Bal_Harbour_Village,Florida,33154.0,District 4,2017-05-23T04:00:00.000Z,2017-05-23T04:00:00.000Z,2017-05-23T04:00:00.000Z,CLOSED,MIAMI,25.896969,-80.125006,WALKIN,0,0.0
2580577,2580578,ANIMAL SERVICES DOG TAG,Citations_and_Tags,Citations_and_Tags,10240 COLLINS AVE,Bal_Harbour_Village,Florida,33154.0,District 4,2017-12-15T05:00:00.000Z,2017-12-15T05:00:00.000Z,2017-12-15T05:00:00.000Z,CLOSED,MIAMI,25.896969,-80.125006,WALKIN,0,0.0
2721053,2721054,ANIMAL SERVICES DOG TAG,Citations_and_Tags,Citations_and_Tags,10240 COLLINS AVE,Bal_Harbour_Village,Florida,33154.0,District 4,2017-05-23T04:00:00.000Z,2017-05-23T04:00:00.000Z,2017-05-23T04:00:00.000Z,CLOSED,MIAMI,25.896969,-80.125006,WALKIN,0,0.0
2904597,2904598,ANIMAL SERVICES DOG TAG,Citations_and_Tags,Citations_and_Tags,10240 COLLINS AVE,Bal_Harbour_Village,Florida,33154.0,District 4,2017-12-15T05:00:00.000Z,2017-12-15T05:00:00.000Z,2017-12-15T05:00:00.000Z,CLOSED,MIAMI,25.896969,-80.125006,WALKIN,0,0.0
3045073,3045074,ANIMAL SERVICES DOG TAG,Citations_and_Tags,Citations_and_Tags,10240 COLLINS AVE,Bal_Harbour_Village,Florida,33154.0,District 4,2017-05-23T04:00:00.000Z,2017-05-23T04:00:00.000Z,2017-05-23T04:00:00.000Z,CLOSED,MIAMI,25.896969,-80.125006,WALKIN,0,0.0
3228617,3228618,ANIMAL SERVICES DOG TAG,Citations_and_Tags,Citations_and_Tags,10240 COLLINS AVE,Bal_Harbour_Village,Florida,33154.0,District 4,2017-12-15T05:00:00.000Z,2017-12-15T05:00:00.000Z,2017-12-15T05:00:00.000Z,CLOSED,MIAMI,25.896969,-80.125006,WALKIN,0,0.0
3369093,3369094,ANIMAL SERVICES DOG TAG,Citations_and_Tags,Citations_and_Tags,10240 COLLINS AVE,Bal_Harbour_Village,Florida,33154.0,District 4,2017-05-23T04:00:00.000Z,2017-05-23T04:00:00.000Z,2017-05-23T04:00:00.000Z,CLOSED,MIAMI,25.896969,-80.125006,WALKIN,0,0.0
3552637,3552638,ANIMAL SERVICES DOG TAG,Citations_and_Tags,Citations_and_Tags,10240 COLLINS AVE,Bal_Harbour_Village,Florida,33154.0,District 4,2017-12-15T05:00:00.000Z,2017-12-15T05:00:00.000Z,2017-12-15T05:00:00.000Z,CLOSED,MIAMI,25.896969,-80.125006,WALKIN,0,0.0

In [30]:
service_df.loc[(service_df['goal_days']==0) | (service_df['goal_days']==180)]

,id,issue_type,case_owner,case_owner_description,street_address,city,state,zip_code,neighborhood_district,ticket_created_date_time,ticket__last_update_date_time,ticket_closed_date_time,ticket_status,location_city,latitude,longitude,method_received,goal_days,actual_completed_days
6,7,ANIMAL SERVICES DOG TAG CHECK,Enforcement_Section-3-36,Enforcement_Section-3-36,28200 SW 126TH CT,Miami_Dade_County,Florida,33033.0,District 9,2017-01-04T05:00:00.000Z,2017-01-07T05:00:00.000Z,2017-01-07T05:00:00.000Z,CLOSED,MIAMI,25.505241,-80.395786,PHONE,0,3.0
7,8,INJURED ANIMAL,Enforcement_Section-3-36,Enforcement_Section-3-36,6620 W 2ND CT,City_of_Hialeah,Florida,33012.0,District 1,2017-01-04T05:00:00.000Z,2017-01-04T05:00:00.000Z,2017-01-04T05:00:00.000Z,CLOSED,MIAMI,25.882716,-80.289545,PHONE,180,0.0
12,13,FAILURE TO OBTAIN ZONING PERMIT,Regulatory_and_Economic_Resources,Regulatory and Economic Resources,19370 SW 125TH AVE,Miami_Dade_County,Florida,33177.0,District 9,2017-01-04T05:00:00.000Z,2017-01-05T05:00:00.000Z,2017-01-05T05:00:00.000Z,CLOSED,MIAMI,25.587365,-80.395696,XTERFACE,180,1.0
23,24,STRAY / DOG-AT-LARGE,Enforcement_Section-3-36,Enforcement_Section-3-36,4700 NW 167TH ST,City_of_Miami_Gardens,Florida,33014.0,District 1,2017-01-04T05:00:00.000Z,2017-01-04T05:00:00.000Z,2017-01-04T05:00:00.000Z,CLOSED,MIAMI,25.924256,-80.276872,PHONE,180,0.0
25,26,STRAY / DOG-AT-LARGE,Enforcement_Section-3-36,Enforcement_Section-3-36,140 NW 163RD ST,Miami_Dade_County,Florida,33169.0,District 2,2017-01-04T05:00:00.000Z,2017-01-26T05:00:00.000Z,2017-01-26T05:00:00.000Z,CLOSED,MIAMI,25.924072,-80.203251,PHONE,180,22.0
33,34,ANIMAL SERVICES DOG TAG,Citations_and_Tags,Citations_and_Tags,7454 SW 129TH CT,Miami_Dade_County,Florida,33183.0,District 1,2017-01-04T05:00:00.000Z,2017-01-04T05:00:00.000Z,2017-01-04T05:00:00.000Z,CLOSED,MIAMI,25.697492,-80.403660,WALKIN,0,0.0
37,38,ANIMAL SERVICES DOG TAG,Citations_and_Tags,Citations_and_Tags,14377 SW 135TH AVE,Miami_Dade_County,Florida,33186.0,District 9,2017-01-04T05:00:00.000Z,2017-01-04T05:00:00.000Z,2017-01-04T05:00:00.000Z,CLOSED,MIAMI,25.633915,-80.412333,WALKIN,0,0.0
41,42,ANIMAL CRUELTY INVESTIGATION,Enforcement_Section-3-36,Enforcement_Section-3-36,4620 SW 101ST AVE,Miami_Dade_County,Florida,33165.0,District 1,2017-01-04T05:00:00.000Z,2017-01-05T05:00:00.000Z,2017-01-05T05:00:00.000Z,CLOSED,MIAMI,25.724802,-80.358712,PHONE,180,1.0
42,43,STRAY / DOG-AT-LARGE,Enforcement_Section-3-36,Enforcement_Section-3-36,23435 SW 127TH AVE,Miami_Dade_County,Florida,33032.0,District 8,2017-01-04T05:00:00.000Z,2017-01-26T05:00:00.000Z,2017-01-26T05:00:00.000Z,CLOSED,MIAMI,25.549183,-80.396001,PHONE,180,22.0
52,53,LOST PET,Citations_and_Tags,Citations_and_Tags,2001 SW 84TH AVE,Miami_Dade_County,Florida,33155.0,District 1,2017-01-04T05:00:00.000Z,2017-01-06T05:00:00.000Z,2017-01-06T05:00:00.000Z,CLOSED,MIAMI,25.751503,-80.331410,PHONE,180,2.0
56,57,STRUCTURE MAINTENANCE - UPKEEP,Regulatory_and_Economic_Resources,Regulatory and Economic Resources,19561 NW 60TH CT,Miami_Dade_County,Florida,33015.0,District 1,2017-01-04T05:00:00.000Z,2017-02-06T05:00:00.000Z,2017-02-06T05:00:00.000Z,CLOSED,MIAMI,25.950885,-80.299565,XTERFACE,180,33.0
64,65,LOST PET,Citations_and_Tags,Citations_and_Tags,20032 SW 123RD DR,Miami_Dade_County,Florida,33177.0,District 9,2017-01-04T05:00:00.000Z,2017-01-06T05:00:00.000Z,2017-01-06T05:00:00.000Z,CLOSED,MIAMI,25.580177,-80.392750,PHONE,180,2.0
70,71,PET ACCOUNT UPDATE,Citations_and_Tags,Citations_and_Tags,12011 SW 178TH TER,Miami_Dade_County,Florida,33177.0,District 9,2017-01-04T05:00:00.000Z,2017-01-05T05:00:00.000Z,2017-01-05T05:00:00.000Z,CLOSED,MIAMI,25.602834,-80.387653,PHONE,180,1.0
72,73,SETBACK VIOLATIONS,Regulatory_and_Economic_Resources,Regulatory and Economic Resources,19561 NW 60TH CT,Miami_Dade_County,Florida,33015.0,District 1,2017-01-04T05:00:00.000Z,2017-02-06T05:00:00.000Z,2017-02-06T05:00:00.000Z,CLOSED,MIAMI,25.950885,-80.299565,XTERFACE,180,33.0
76,77,DEAD ANIMAL PICKUP MD,Enforcement_Section-3-36,Enforcement_Section-3-36,SW 167TH AVE & SW 88TH ST,Miami_Dade_County,Florida,33193.0,District 1,2017-01-04T05:00:00.000Z,2017-01-04T05:00:00.000Z,2017-01-04T05:00:00.000Z,CLOSED,MIAMI,25.683903,-80.461992,INHOUSE,180,0.0
83,84,STRAY / DOG-AT-LARGE,Enforcement_Section-3-36,Enforcement_Section-3-36,27041 SW 119TH CT,Miami_Dade_County,Florida,33032.0,District 9,2017-01-04T05:00:00.000Z,2017-01-26T05:00:00.000Z,2017-01-26T05:00:00.000Z,CLOSED,MIAMI,25.515979,-80.384340,PHONE,180,22.0
84,85,PET ACCOUNT UPDATE,Citations_and_Tags,Citations_and_Tags,9373 FONTAINEBLEAU BLVD,Miami_Dade_County,Florida,33172.0,District 1,2017-01-04T05:00:00.000Z,2017-01-05T05:00:00.000Z,2017-01-05T05:00:00.000Z,CLOSED,MIAMI,25.774762,-80.347643,PHONE,180,1.0
85,86,INJURED ANIMAL,Enforcement_Section-3-36,Enforcement_Section-3-36,626 EUCLID AVE,City_of_Miami_Beach,Florida,33139.0,District 5,2017-01-04T05:00:00.000Z,2017-01-04T05:00:00.000Z,2017-01-04T05:00:00.000Z,CLOSED,MIAMI,25.776392,-80.135301,PHONE,180,0.0
101,102,STRAY / DOG-AT-LARGE,Enforcement_Section-3-36,Enforcement_Section-3-36,14400 BUCHANAN ST,Miami_Dade_County,Florida,33176.0,District 9,2017-01-04T05:00:00.000Z,2017-01-26T05:00:00.000Z,2017-01-26T05:00:00.000Z,CLOSED,MIAMI,25.634706,-80.370094,PHONE,180,22.0
102,103,FAILURE TO OBTAIN A CERTIFICATE OF USE,Regulatory_and_Economic_Resources,Regulatory and Economic Resources,4100 NW 22ND AVE,Miami_Dade_County,Florida,33142.0,District 3,2017-01-04T05:00:00.000Z,2017-02-13T05:00:00.000Z,2017-02-13T05:00:00.000Z,CLOSED,MIAMI,25.813348,-80.232549,XTERFACE,180,40.0
118,119,ANIMAL CRUELTY INVESTIGATION,Enforcement_Section-3-36,Enforcement_Section-3-36,3213 SW 24TH ST,City_of_Miami,Florida,33145.0,District 7,2017-01-04T05:00:00.000Z,2017-01-04T05:00:00.000Z,2017-01-04T05:00:00.000Z,CLOSED,MIAMI,25.746685,-80.246593,PHONE,180,0.0
124,125,PET ACCOUNT UPDATE,Citations_and_Tags,Citations_and_Tags,11653 NW 78TH ST,City_of_Doral,Florida,33178.0,District 1,2017-01-04T05:00:00.000Z,2017-01-05T05:00:00.000Z,2017-01-05T05:00:00.000Z,CLOSED,MIAMI,25.844346,-80.385927,PHONE,180,1.0
125,126,PET ACCOUNT UPDATE,Citations_and_Tags,Citations_and_Tags,7012 SW 149TH TER,City_of_Palmetto_Bay,Florida,33158.0,District 8,2017-01-04T05:00:00.000Z,2017-01-05T05:00:00.000Z,2017-01-05T05:00:00.000Z,CLOSED,MIAMI,25.631871,-80.307881,PHONE,180,1.0
126,127,PET ACCOUNT UPDATE,Citations_and_Tags,Citations_and_Tags,14348 SW 165TH ST,Miami_Dade_County,Florida,33177.0,District 9,2017-01-04T05:00:00.000Z,2017-01-05T05:00:00.000Z,2017-01-05T05:00:00.000Z,CLOSED,MIAMI,25.613617,-80.424903,PHONE,180,1.0
130,131,STRAY DOG PICK UP - MD,Enforcement_Section-3-36,Enforcement_Section-3-36,2250 NW 63RD ST,Miami_Dade_County,Florida,33147.0,District 3,2017-01-04T05:00:00.000Z,2017-01-08T05:00:00.000Z,2017-01-08T05:00:00.000Z,CLOSED,MIAMI,25.832239,-80.233596,PHONE,180,4.0
132,133,PET ACCOUNT UPDATE,Citations_and_Tags,Citations_and_Tags,13823 SW 23RD TER,Miami_Dade_County,Florida,33175.0,District 1,2017-01-04T05:00:00.000Z,2017-01-05T05:00:00.000Z,2017-01-05T05:00:00.000Z,CLOSED,MIAMI,25.745981,-80.418923,WALKIN,180,1.0
136,137,PET ACCOUNT UPDATE,Citations_and_Tags,Citations_and_Tags,945 NW 22ND PL,City_of_Miami,Florida,33125.0,District 5,2017-01-04T05:00:00.000Z,2017-01-05T05:00:00.000Z,2017-01-05T05:00:00.000Z,CLOSED,MIAMI,25.782240,-80.232419,PHONE,180,1.0
139,140,PET ACCOUNT UPDATE,Citations_and_Tags,Citations_and_Tags,16040 SW 199TH AVE,Miami_Dade_County,Florida,33187.0,District 9,2017-01-04T05:00:00.000Z,2017-01-05T05:00:00.000Z,2017-01-05T05:00:00.000Z,CLOSED,MIAMI,25.614593,-80.515814,PHONE,180,1.0
142,143,PET ACCOUNT UPDATE,Citations_and_Tags,Citations_and_Tags,8092 W 18TH AVE,City_of_Hialeah,Florida,33014.0,District 1,2017-01-04T05:00:00.000Z,2017-01-05T05:00:00.000Z,2017-01-05T05:00:00.000Z,CLOSED,MIAMI,25.896100,-80.320421,PHONE,180,1.0
158,159,ANIMAL SERVICES DOG TAG CHECK,Enforcement_Section-3-36,Enforcement_Section-3-36,27951 SW 168TH CT,Miami_Dade_County,Florida,33031.0,District 8,2017-01-04T05:00:00.000Z,2017-01-05T05:00:00.000Z,2017-01-05T05:00:00.000Z,CLOSED,MIAMI,25.506969,-80.464062,PHONE,0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3563946,3563947,DEAD ANIMAL PICKUP MD,Enforcement_Section-3-36,Enforcement_Section-3-36,N KENDALL DR & SW 113TH CT,Miami_Dade_County,Florida,33176.0,District 1,2017-12-31T05:00:00.000Z,2018-01-02T05:00:00.000Z,2018-01-02T05:00:00.000Z,CLOSED,MIAMI,25.686552,-80.379159,INHOUSE,180,2.0
3563947,3563948,STRAY / DOG-AT-LARGE,Enforcement_Section-3-36,Enforcement_Section-3-36,4766 SW 142ND CT,Miami_Dade_County,Florida,33175.0,District 1,2017-12-31T05:00:00.000Z,2018-01-20T05:00:00.000Z,2018-01-20T05:00:00.000Z,CLOSED,MIAMI,25.722879,-80.423998,WEB,180,20.0
3563957,3563958,ANIMAL CRUELTY FOLLOW-UP,Enforcement_Section-3-36,Enforcement_Section-3-36,5984 SW 41ST ST,Miami_Dade_County,Florida,33155.0,District 7,2017-12-31T05:00:00.000Z,2018-01-15T05:00:00.000Z,2018-01-15T05:00:00.000Z,CLOSED,MIAMI,25.732857,-80.292042,INHOUSE,180,15.0
3563958,3563959,ANIMAL CRUELTY FOLLOW-UP,Enforcement_Section-3-36,Enforcement_Section-3-36,12745 NW 17TH PL,Miami_Dade_County,Florida,33167.0,District 2,2017-12-31T05:00:00.000Z,2018-01-02T05:00:00.000Z,2018-01-02T05:00:00.000Z,CLOSED,MIAMI,25.891170,-80.228513,INHOUSE,180,2.0
3563963,3563964,ANIMAL BITE TO A PERSON,Enforcement_Section-3-36,Enforcement_Section-3-36,24900 SW 119TH AVE,Miami_Dade_County,Florida,33032.0,District 8,2017-12-31T05:00:00.000Z,2017-12-31T05:00:00.000Z,2017-12-31T05:00:00.000Z,CLOSED,MIAMI,25.535875,-80.384510,INHOUSE,180,0.0
3563964,3563965,ASU POLICE ASSISTANCE,Enforcement_Section-3-36,Enforcement_Section-3-36,11920 SW 179TH TER,Miami_Dade_County,Florida,33177.0,District 9,2017-12-31T05:00:00.000Z,2017-12-31T05:00:00.000Z,2017-12-31T05:00:00.000Z,CLOSED,MIAMI,25.601705,-80.385619,INHOUSE,180,0.0
3563968,3563969,STRAY / DOG-AT-LARGE,Enforcement_Section-3-36,Enforcement_Section-3-36,191 NW 50TH ST,City_of_Miami,Florida,33127.0,District 3,2017-12-31T05:00:00.000Z,2017-12-31T05:00:00.000Z,2017-12-31T05:00:00.000Z,CLOSED,MIAMI,25.821761,-80.199517,PHONE,180,0.0
3563969,3563970,PET ACCOUNT UPDATE,Citations_and_Tags,Citations_and_Tags,7090 NW 177TH ST,Miami_Dade_County,Florida,33015.0,District 1,2017-12-30T05:00:00.000Z,2018-01-02T05:00:00.000Z,2018-01-02T05:00:00.000Z,CLOSED,MIAMI,25.934281,-80.318204,PHONE,180,3.0
3563974,3563975,ASU POLICE ASSISTANCE,Enforcement_Section-3-36,Enforcement_Section-3-36,6780 SW 44TH ST,Miami_Dade_County,Florida,33155.0,District 7,2017-12-31T05:00:00.000Z,2017-12-31T05:00:00.000Z,2017-12-31T05:00:00.000Z,CLOSED,MIAMI,25.729474,-80.303455,INHOUSE,180,0.0
3563987,3563988,DEAD ANIMAL PICKUP MD,Enforcement_Section-3-36,Enforcement_Section-3-36,11201 SW 88TH ST,Miami_Dade_County,Florida,33176.0,District 1,2017-12-31T05:00:00.000Z,2018-01-03T05:00:00.000Z,2018-01-03T05:00:00.000Z,CLOSED,MIAMI,25.689918,-80.374303,WEB,180,3.0
3563996,3563997,ASU POLICE ASSISTANCE,Enforcement_Section-3-36,Enforcement_Section-3-36,760 OPA LOCKA BLVD,City_of_Opa-Locka,Florida,33054.0,District 2,2017-12-30T05:00:00.000Z,2017-12-30T05:00:00.000Z,2017-12-30T05:00:00.000Z,CLOSED,MIAMI,25.899982,-80.249978,PHONE,180,0.0
3563997,3563998,PET ACCOUNT UPDATE,Citations_and_Tags,Citations_and_Tags,50 TRUXTON DR,City_of_Miami_Springs,Florida,33166.0,District 6,2017-12-30T05:00:00.000Z,2018-01-02T05:00:00.000Z,2018-01-02T05:00:00.000Z,CLOSED,MIAMI,25.814163,-80.298779,PHONE,180,3.0
3564005,3564006,PET ACCOUNT UPDATE,Citations_and_Tags,Citations_and_Tags,2485 NW 15TH ST,City_of_Miami,Florida,33125.0,District 5,2017-12-30T05:00:00.000Z,2018-01-02T05:00:00.000Z,2018-01-02T05:00:00.000Z,CLOSED,MIAMI,25.788025,-80.237145,PHONE,180,3.0
3564006,3564007,STRAY / DOG-AT-LARGE,Enforcement_Section-3-36,Enforcement_Section-3-36,15361 SW 143RD AVE,Miami_Dade_County,Florida,33177.0,District 9,2017-12-30T05:00:00.000Z,2018-01-24T05:00:00.000Z,2018-01-24T05:00:00.000Z,CLOSED,MIAMI,25.624814,-80.426392,PHONE,180,25.0
3564015,3564016,ASU POLICE ASSISTANCE,Enforcement_Section-3-36,Enforcement_Section-3-36,10000 SW 142ND AVE,Miami_Dade_County,Florida,33186.0,District 1,2017-12-30T05:00:00.000Z,2017-12-30T05:00:00.000Z,2017-12-30T05:00:00.000Z,CLOSED,MIAMI,25.674636,-80.422925,INHOUSE,180,0.0
3564019,3564020,ANIMAL BITE TO A PERSON,Enforcement_Section-3-36,Enforcement_Section-3-36,881 WEST DR,City_of_Opa-Locka,Florida,33054.0,District 2,2017-12-30T05:00:00.000Z,2017-12-30T05:00:00.000Z,2017-12-30T05:00:00.000Z,CLOSED,MIAMI,25.899802,-80.250457,PHONE,180,0.0
3564022,3564023,ASU POLICE ASSISTANCE,Enforcement_Section-3-36,Enforcement_Section-3-36,SW 16TH AVE & SW 8TH ST,City_of_Miami,Florida,33135.0,District 5,2017-12-30T05:00:00.000Z,2017-12-30T05:00:00.000Z,2017-12-30T05:00:00.000Z,CLOSED,MIAMI,25.765661,-80.221133,PHONE,180,0.0
3564023,3564024,ASU POLICE ASSISTANCE,Enforcement_Section-3-36,Enforcement_Section-3-36,1077 NW 24TH ST,City_of_Miami,Florida,33127.0,District 3,2017-12-30T05:00:00.000Z,2017-12-30T05:00:00.000Z,2017-12-30T05:00:00.000Z,CLOSED,MIAMI,25.799698,-80.212793,PHONE,180,0.0
3564093,3564094,ASU POLICE ASSISTANCE,Enforcement_Section-3-36,Enforcement_Section-3-36,935 W 69TH PL,City_of_Hialeah,Florida,33014.0,District 1,2017-12-31T05:00:00.000Z,2017-12-31T05:00:00.000Z,2017-12-31T05:00:00.000Z,CLOSED,MIAMI,25.886050,-80.302290,PHONE,180,0.0
3564135,3564136,INJURED ANIMAL,Enforcement_Section-3-36,Enforcement_Section-3-36,17301 NW 17TH AVE,City_of_Miami_Gardens,Florida,33056.0,District 1,2017-12-30T05:00:00.000Z,2017-12-30T05:00:00.000Z,2017-12-30T05:00:00.000Z,CLOSED,MIAMI,25.932371,-80.228506,PHONE,180,0.0
3564140,3564141,INJURED ANIMAL,Enforcement_Section-3-36,Enforcement_Section-3-36,17275 SW 299TH ST,Miami_Dade_County,Florida,33030.0,District 8,2017-12-30T05:00:00.000Z,2017-12-30T05:00:00.000Z,2017-12-30T05:00:00.000Z,CLOSED,MIAMI,25.489359,-80.471091,PHONE,180,0.0
3564141,3564142,ANIMAL CRUELTY INVESTIGATION,Enforcement_Section-3-36,Enforcement_Section-3-36,15250 SW 134TH PL,Miami_Dade_County,Florida,33177.0,District 9,2017-12-30T05:00:00.000Z,2018-01-18T05:00:00.000Z,2018-01-18T05:00:00.000Z,CLOSED,MIAMI,25.625927,-80.411399,PHONE,180,19.0
3564159,3564160,INJURED ANIMAL,Enforcement_Section-3-36,Enforcement_Section-3-36,6272 SW 164TH PATH,Miami_Dade_County,Florida,33193.0,District 1,2017-12-30T05:00:00.000Z,2017-12-30T05:00:00.000Z,2017-12-30T05:00:00.000Z,CLOSED,MIAMI,25.706834,-80.460255,PHONE,180,0.0
3564160,3564161,INJURED ANIMAL,Enforcement_Section-3-36,Enforcement_Section-3-36,2474 NW 78TH ST,Miami_Dade_County,Florida,33147.0,District 2,2017-12-30T05:00:00.000Z,2017-12-30T05:00:00.000Z,2017-12-30T05:00:00.000Z,CLOSED,MIAMI,25.845421,-80.239136,PHONE,180,0.0
3564167,3564168,DEAD ANIMAL PICKUP MD,Enforcement_Section-3-36,Enforcement_Section-3-36,13001 SW 26TH ST,Miami_Dade_County,Florida,33175.0,District 1,2017-12-30T05:00:00.000Z,2018-01-02T05:00:00.000Z,2018-01-02T05:00:00.000Z,CLOSED,MIAMI,25.744758,-80.405659,PHONE,180,3.0
3564169,3564170,FAILURE TO OBTAIN ZONING PERMIT,Regulatory_and_Economic_Resources,Regulatory and Economic Resources,3310 NW 81ST TER,Miami_Dade_County,Florida,33147.0,District 2,2017-12-30T05:00:00.000Z,2018-01-16T05:00:00.000Z,2018-01-16T05:00:00.000Z,CLOSED,MIAMI,25.847712,-80.252476,PHONE,180,17.0
3564173,3564174,STRAY DOG PICK UP - MD,Enforcement_Section-3-36,Enforcement_Section-3-36,14840 NARANJA LAKES BLVD,Miami_Dade_County,Florida,33032.0,District 9,2017-12-30T05:00:00.000Z,2017-12-31T05:00:00.000Z,2017-12-31T05:00:00.000Z,CLOSED,MIAMI,25.509371,-80.433369,PHONE,180,1.0
3564210,3564211,DEAD ANIMAL PICKUP MD,Enforcement_Section-3-36,Enforcement_Section-3-36,33053 SW 202ND AVE,Miami_Dade_County,Florida,33034.0,District 9,2017-12-31T05:00:00.000Z,2018-01-06T05:00:00.000Z,2018-01-06T05:00:00.000Z,CLOSED,MIAMI,25.459978,-80.517673,WEB,180,6.0
3564213,3564214,ANIMAL CRUELTY FOLLOW-UP,Enforcement_Section-3-36,Enforcement_Section-3-36,11765 SW 223RD ST,Miami_Dade_County,Florida,33170.0,District 9,2017-12-31T05:00:00.000Z,2018-01-17T05:00:00.000Z,2018-01-17T05:00:00.000Z,CLOSED,MIAMI,25.560256,-80.381620,INHOUSE,180,17.0
3564217,3564218,ANIMAL BITE TO A PERSON,Enforcement_Section-3-36,Enforcement_Section-3-36,935 W 69TH PL,City_of_Hialeah,Florida,33014.0,District 1,2017-12-31T05:00:00.000Z,2018-01-04T05:00:00.000Z,2017-12-31T05:00:00.000Z,CLOSED,MIAMI,25.886050,-80.302290,PHONE,180,0.0

In [31]:
#create df for mean 0 set to 1 
city_avg_one = city_avg[['city','case_owner','issue_type', 'mean']]
city_avg_one.head()

,city,case_owner,issue_type,mean
0,Bal_Harbour_Village,Citations_and_Tags,ANIMAL SERVICES DOG TAG,0.000000
1,Bal_Harbour_Village,Citations_and_Tags,PET ACCOUNT UPDATE,1.571429
2,Bal_Harbour_Village,Enforcement_Section-3-36,DANGEROUS DOG INVESTIGATION,36.000000
3,Bal_Harbour_Village,Enforcement_Section-3-36,DEAD ANIMAL PICKUP MD,0.000000
4,Bal_Harbour_Village,Enforcement_Section-3-36,INJURED ANIMAL,0.000000

In [32]:
#replace 0 mean value with 1
city_avg_one['mean'] = city_avg_one['mean'].replace(0,1)

In [33]:
city_avg_one.head()

,city,case_owner,issue_type,mean
0,Bal_Harbour_Village,Citations_and_Tags,ANIMAL SERVICES DOG TAG,1.000000
1,Bal_Harbour_Village,Citations_and_Tags,PET ACCOUNT UPDATE,1.571429
2,Bal_Harbour_Village,Enforcement_Section-3-36,DANGEROUS DOG INVESTIGATION,36.000000
3,Bal_Harbour_Village,Enforcement_Section-3-36,DEAD ANIMAL PICKUP MD,1.000000
4,Bal_Harbour_Village,Enforcement_Section-3-36,INJURED ANIMAL,1.000000

In [34]:
#create df with mean 0 removed
city_avg_no_zero = city_avg.loc[city_avg['mean'] != 0]
city_avg_no_zero.head()

,city,case_owner,issue_type,mean
1,Bal_Harbour_Village,Citations_and_Tags,PET ACCOUNT UPDATE,1.571429
2,Bal_Harbour_Village,Enforcement_Section-3-36,DANGEROUS DOG INVESTIGATION,36.000000
5,Bal_Harbour_Village,Public_Works_traffic_Signals_And_Signs-15-60,TRAFFIC SIGNAL BULB BURNED OUT,13.000000
6,Bal_Harbour_Village,Public_Works_traffic_Signals_And_Signs-15-60,TRAFFIC SIGNAL RED DISPLAY TOO LONG OR GREEN T...,10.000000
7,Bal_Harbour_Village,Solid_Waste_Management,MOSQUITO INSPECTION REQUEST,1.882353

In [35]:
#remove 0 mean from total avg
total_avg_no_zero = total_avg_rename.loc[total_avg_rename['total_mean'] != 0]
total_avg_no_zero.head()

             case_owner                issue_type  total_mean
0  COM_Code_Enforcement  ILLEGAL DUMPING / LITTER   28.424989
1    Citations_and_Tags   ANIMAL SERVICES DOG TAG    0.004464
2    Citations_and_Tags                 FOUND PET   10.347826
3    Citations_and_Tags                  LOST PET    4.403636
4    Citations_and_Tags        PET ACCOUNT UPDATE    1.501179

In [36]:
#check where negative values are from DELETE THIS
city_avg_no_zero.loc[city_avg_no_zero['mean'] < 0]
service_df.loc[(service_df['city'] == 'Miami_Dade_County') & (service_df['issue_type'] == 'BULKY TRASH UPDATE') ]

,id,issue_type,case_owner,case_owner_description,street_address,city,state,zip_code,neighborhood_district,ticket_created_date_time,ticket__last_update_date_time,ticket_closed_date_time,ticket_status,location_city,latitude,longitude,method_received,goal_days,actual_completed_days
75,76,BULKY TRASH UPDATE,Solid_Waste_Management,Solid Waste Management,9840 SW 155TH AVE,Miami_Dade_County,Florida,33196.0,District 1,2017-01-04T05:00:00.000Z,2017-01-06T05:00:00.000Z,2017-01-06T05:00:00.000Z,CLOSED,MIAMI,25.675051,-80.447827,PHONE,30,2.0
570,571,BULKY TRASH UPDATE,Solid_Waste_Management,Solid Waste Management,17328 NW 62ND PL,Miami_Dade_County,Florida,33015.0,District 1,2017-01-05T05:00:00.000Z,2017-01-05T05:00:00.000Z,2017-01-05T05:00:00.000Z,CLOSED,MIAMI,25.932141,-80.303287,PHONE,30,0.0
696,697,BULKY TRASH UPDATE,Solid_Waste_Management,Solid Waste Management,15843 SW 71ST ST,Miami_Dade_County,Florida,33193.0,District 1,2017-01-05T05:00:00.000Z,2017-01-05T05:00:00.000Z,2017-01-05T05:00:00.000Z,CLOSED,MIAMI,25.699934,-80.448978,PHONE,30,0.0
1059,1060,BULKY TRASH UPDATE,Solid_Waste_Management,Solid Waste Management,3034 NW 33RD ST,Miami_Dade_County,Florida,33142.0,District 2,2017-01-03T05:00:00.000Z,2017-01-04T05:00:00.000Z,2017-01-04T05:00:00.000Z,CLOSED,MIAMI,25.805910,-80.244999,PHONE,30,1.0
1317,1318,BULKY TRASH UPDATE,Solid_Waste_Management,Solid Waste Management,21920 SW 118TH CT,Miami_Dade_County,Florida,33170.0,District 9,2017-01-03T05:00:00.000Z,2017-01-12T05:00:00.000Z,2017-01-06T05:00:00.000Z,CLOSED,MIAMI,25.563099,-80.383838,PHONE,30,3.0
1375,1376,BULKY TRASH UPDATE,Solid_Waste_Management,Solid Waste Management,5248 SW 91ST AVE,Miami_Dade_County,Florida,33165.0,District 1,2017-01-03T05:00:00.000Z,2017-01-04T05:00:00.000Z,2017-01-04T05:00:00.000Z,CLOSED,MIAMI,25.719675,-80.342468,PHONE,30,1.0
1517,1518,BULKY TRASH UPDATE,Solid_Waste_Management,Solid Waste Management,1497 NE 148TH ST,Miami_Dade_County,Florida,33161.0,District 2,2017-01-03T05:00:00.000Z,2017-01-04T05:00:00.000Z,2017-01-04T05:00:00.000Z,CLOSED,MIAMI,25.911919,-80.169417,PHONE,30,1.0
1537,1538,BULKY TRASH UPDATE,Solid_Waste_Management,Solid Waste Management,5522 SW 158TH CT,Miami_Dade_County,Florida,33185.0,District 1,2017-01-03T05:00:00.000Z,2017-01-06T05:00:00.000Z,2017-01-06T05:00:00.000Z,CLOSED,MIAMI,25.714101,-80.449673,PHONE,30,3.0
1554,1555,BULKY TRASH UPDATE,Solid_Waste_Management,Solid Waste Management,2547 NE 183RD ST,Miami_Dade_County,Florida,33160.0,District 4,2017-01-03T05:00:00.000Z,2017-01-26T05:00:00.000Z,2017-01-06T05:00:00.000Z,CLOSED,MIAMI,25.944781,-80.149806,PHONE,30,3.0
1801,1802,BULKY TRASH UPDATE,Solid_Waste_Management,Solid Waste Management,10231 SW 160TH TER,Miami_Dade_County,Florida,33157.0,District 9,2017-01-03T05:00:00.000Z,2017-01-04T05:00:00.000Z,2017-01-04T05:00:00.000Z,CLOSED,MIAMI,25.620397,-80.358419,PHONE,30,1.0
1852,1853,BULKY TRASH UPDATE,Solid_Waste_Management,Solid Waste Management,16100 SW 153RD AVE,Miami_Dade_County,Florida,33187.0,District 9,2017-01-03T05:00:00.000Z,2017-01-17T05:00:00.000Z,2017-01-06T05:00:00.000Z,CLOSED,MIAMI,25.616784,-80.441098,PHONE,30,3.0
1890,1891,BULKY TRASH UPDATE,Solid_Waste_Management,Solid Waste Management,11233 SW 151ST PL,Miami_Dade_County,Florida,33196.0,District 1,2017-01-03T05:00:00.000Z,2017-01-05T05:00:00.000Z,2017-01-05T05:00:00.000Z,CLOSED,MIAMI,25.662732,-80.439183,EMAIL,30,2.0
1959,1960,BULKY TRASH UPDATE,Solid_Waste_Management,Solid Waste Management,1621 SW 97TH CT,Miami_Dade_County,Florida,33165.0,District 1,2017-01-03T05:00:00.000Z,2017-01-06T05:00:00.000Z,2017-01-06T05:00:00.000Z,CLOSED,MIAMI,25.753816,-80.352396,PHONE,30,3.0
2148,2149,BULKY TRASH UPDATE,Solid_Waste_Management,Solid Waste Management,15625 NE 4TH AVE,Miami_Dade_County,Florida,33162.0,District 2,2017-01-05T05:00:00.000Z,2017-01-06T05:00:00.000Z,2017-01-06T05:00:00.000Z,CLOSED,MIAMI,25.918854,-80.191241,PHONE,30,1.0
2309,2310,BULKY TRASH UPDATE,Solid_Waste_Management,Solid Waste Management,10505 SW 128TH TER,Miami_Dade_County,Florida,33176.0,District 8,2017-01-05T05:00:00.000Z,2017-01-06T05:00:00.000Z,2017-01-06T05:00:00.000Z,CLOSED,MIAMI,25.649954,-80.365274,PHONE,30,1.0
2354,2355,BULKY TRASH UPDATE,Solid_Waste_Management,Solid Waste Management,450 SW 131ST CT,Miami_Dade_County,Florida,33184.0,District 1,2017-01-05T05:00:00.000Z,2017-01-06T05:00:00.000Z,2017-01-06T05:00:00.000Z,CLOSED,MIAMI,25.763088,-80.409164,PHONE,30,1.0
2404,2405,BULKY TRASH UPDATE,Solid_Waste_Management,Solid Waste Management,10600 SW 128TH TER,Miami_Dade_County,Florida,33176.0,District 8,2017-01-05T05:00:00.000Z,2017-01-06T05:00:00.000Z,2017-01-06T05:00:00.000Z,CLOSED,MIAMI,25.649437,-80.366411,PHONE,30,1.0
2428,2429,BULKY TRASH UPDATE,Solid_Waste_Management,Solid Waste Management,4622 SW 12TH ST,Miami_Dade_County,Florida,33134.0,District 6,2017-01-05T05:00:00.000Z,2017-01-06T05:00:00.000Z,2017-01-06T05:00:00.000Z,CLOSED,MIAMI,25.760381,-80.269800,PHONE,30,1.0
2495,2496,BULKY TRASH UPDATE,Solid_Waste_Management,Solid Waste Management,25314 SW 127TH CT,Miami_Dade_County,Florida,33032.0,District 8,2017-01-05T05:00:00.000Z,2017-01-06T05:00:00.000Z,2017-01-06T05:00:00.000Z,CLOSED,MIAMI,25.531556,-80.397458,PHONE,30,1.0
2575,2576,BULKY TRASH UPDATE,Solid_Waste_Management,Solid Waste Management,809 NW 108TH ST,Miami_Dade_County,Florida,33168.0,District 2,2017-01-05T05:00:00.000Z,2017-01-06T05:00:00.000Z,2017-01-06T05:00:00.000Z,CLOSED,MIAMI,25.873963,-80.212615,PHONE,30,1.0
2611,2612,BULKY TRASH UPDATE,Solid_Waste_Management,Solid Waste Management,20301 NE 13TH CT,Miami_Dade_County,Florida,33179.0,District 1,2017-01-06T05:00:00.000Z,2017-01-09T05:00:00.000Z,2017-01-09T05:00:00.000Z,CLOSED,MIAMI,25.962458,-80.174722,PHONE,30,3.0
2635,2636,BULKY TRASH UPDATE,Solid_Waste_Management,Solid Waste Management,17900 SW 154TH CT,Miami_Dade_County,Florida,33187.0,District 9,2017-01-06T05:00:00.000Z,2017-01-09T05:00:00.000Z,2017-01-09T05:00:00.000Z,CLOSED,MIAMI,25.600214,-80.443021,PHONE,30,3.0
2701,2702,BULKY TRASH UPDATE,Solid_Waste_Management,Solid Waste Management,9234 SW 132ND ST,Miami_Dade_County,Florida,33176.0,District 8,2017-01-06T05:00:00.000Z,2017-01-09T05:00:00.000Z,2017-01-09T05:00:00.000Z,CLOSED,MIAMI,25.646419,-80.343642,PHONE,30,3.0
2749,2750,BULKY TRASH UPDATE,Solid_Waste_Management,Solid Waste Management,6340 SW 163RD PL,Miami_Dade_County,Florida,33193.0,District 1,2017-01-06T05:00:00.000Z,2017-01-09T05:00:00.000Z,2017-01-09T05:00:00.000Z,CLOSED,MIAMI,25.706044,-80.458729,PHONE,30,3.0
2810,2811,BULKY TRASH UPDATE,Solid_Waste_Management,Solid Waste Management,15460 SW 256TH ST,Miami_Dade_County,Florida,33032.0,District 8,2017-01-05T05:00:00.000Z,2017-01-06T05:00:00.000Z,2017-01-06T05:00:00.000Z,CLOSED,MIAMI,25.527529,-80.442268,EMAIL,30,1.0
2816,2817,BULKY TRASH UPDATE,Solid_Waste_Management,Solid Waste Management,10815 SW 165TH TER,Miami_Dade_County,Florida,33157.0,District 9,2017-01-05T05:00:00.000Z,2017-01-06T05:00:00.000Z,2017-01-06T05:00:00.000Z,CLOSED,MIAMI,25.615622,-80.368655,PHONE,30,1.0
2881,2882,BULKY TRASH UPDATE,Solid_Waste_Management,Solid Waste Management,12071 SW 126TH TER,Miami_Dade_County,Florida,33186.0,District 9,2017-01-06T05:00:00.000Z,2017-01-09T05:00:00.000Z,2017-01-09T05:00:00.000Z,CLOSED,MIAMI,25.651112,-80.390460,PHONE,30,3.0
2889,2890,BULKY TRASH UPDATE,Solid_Waste_Management,Solid Waste Management,19050 SW 284TH ST,Miami_Dade_County,Florida,33030.0,District 8,2017-01-06T05:00:00.000Z,2017-01-09T05:00:00.000Z,2017-01-09T05:00:00.000Z,CLOSED,MIAMI,25.501743,-80.500515,PHONE,30,3.0
2903,2904,BULKY TRASH UPDATE,Solid_Waste_Management,Solid Waste Management,1021 NW 89TH ST,Miami_Dade_County,Florida,33150.0,District 2,2017-01-06T05:00:00.000Z,2017-01-09T05:00:00.000Z,2017-01-09T05:00:00.000Z,CLOSED,MIAMI,25.856584,-80.214618,PHONE,30,3.0
3075,3076,BULKY TRASH UPDATE,Solid_Waste_Management,Solid Waste Management,19462 NW 54TH PL,Miami_Dade_County,Florida,33055.0,District 1,2017-01-03T05:00:00.000Z,2017-01-03T05:00:00.000Z,2016-01-05T05:00:00.000Z,CLOSED,MIAMI,25.949305,-80.291382,PHONE,30,-364.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3559795,3559796,BULKY TRASH UPDATE,Solid_Waste_Management,Solid Waste Management,18845 NW 82ND CT,Miami_Dade_County,Florida,33015.0,District 1,2017-12-06T05:00:00.000Z,2017-12-07T05:00:00.000Z,2017-12-07T05:00:00.000Z,CLOSED,MIAMI,25.944508,-80.334695,PHONE,30,1.0
3559826,3559827,BULKY TRASH UPDATE,Solid_Waste_Management,Solid Waste Management,13951 SW 72ND TER,Miami_Dade_County,Florida,33183.0,District 1,2017-12-06T05:00:00.000Z,2017-12-07T05:00:00.000Z,2017-12-07T05:00:00.000Z,CLOSED,MIAMI,25.699503,-80.419086,PHONE,30,1.0
3560131,3560132,BULKY TRASH UPDATE,Solid_Waste_Management,Solid Waste Management,11400 SW 40TH ST,Miami_Dade_County,Florida,33165.0,District 1,2017-12-06T05:00:00.000Z,2017-12-07T05:00:00.000Z,2017-12-07T05:00:00.000Z,CLOSED,MIAMI,25.731749,-80.379623,PHONE,30,1.0
3560790,3560791,BULKY TRASH UPDATE,Solid_Waste_Management,Solid Waste Management,14421 NE 16TH AVE,Miami_Dade_County,Florida,33161.0,District 2,2017-12-18T05:00:00.000Z,2017-12-22T05:00:00.000Z,2017-12-22T05:00:00.000Z,CLOSED,MIAMI,25.908836,-80.166922,PHONE,30,4.0
3560855,3560856,BULKY TRASH UPDATE,Solid_Waste_Management,Solid Waste Management,1414 NW 113TH TER,Miami_Dade_County,Florida,33167.0,District 2,2017-12-18T05:00:00.000Z,2017-12-19T05:00:00.000Z,2017-12-19T05:00:00.000Z,CLOSED,MIAMI,25.877974,-80.222912,PHONE,30,1.0
3560974,3560975,BULKY TRASH UPDATE,Solid_Waste_Management,Solid Waste Management,10424 NW 33RD AVE,Miami_Dade_County,Florida,33147.0,District 2,2017-12-18T05:00:00.000Z,2017-12-19T05:00:00.000Z,2017-12-19T05:00:00.000Z,CLOSED,MIAMI,25.869193,-80.253528,PHONE,30,1.0
3561362,3561363,BULKY TRASH UPDATE,Solid_Waste_Management,Solid Waste Management,12305 SW 84TH AVE,Miami_Dade_County,Florida,33156.0,District 8,2017-11-29T05:00:00.000Z,2017-12-05T05:00:00.000Z,2017-12-05T05:00:00.000Z,CLOSED,MIAMI,25.655660,-80.330239,PHONE,30,6.0
3561481,3561482,BULKY TRASH UPDATE,Solid_Waste_Management,Solid Waste Management,7534 SW 113TH CT,Miami_Dade_County,Florida,33173.0,District 1,2017-11-30T05:00:00.000Z,2017-12-05T05:00:00.000Z,2017-12-05T05:00:00.000Z,CLOSED,MIAMI,25.698015,-80.376596,PHONE,30,5.0
3561539,3561540,BULKY TRASH UPDATE,Solid_Waste_Management,Solid Waste Management,12440 SW 218TH ST,Miami_Dade_County,Florida,33170.0,District 9,2017-11-30T05:00:00.000Z,2017-12-05T05:00:00.000Z,2017-12-05T05:00:00.000Z,CLOSED,MIAMI,25.564086,-80.394034,PHONE,30,5.0
3561660,3561661,BULKY TRASH UPDATE,Solid_Waste_Management,Solid Waste Management,14926 SW 23RD WAY,Miami_Dade_County,Florida,33185.0,District 1,2017-11-30T05:00:00.000Z,2017-12-05T05:00:00.000Z,2017-12-05T05:00:00.000Z,CLOSED,MIAMI,25.744653,-80.436754,PHONE,30,5.0
3561709,3561710,BULKY TRASH UPDATE,Solid_Waste_Management,Solid Waste Management,13735 SW 18TH TER,Miami_Dade_County,Florida,33175.0,District 1,2017-11-30T05:00:00.000Z,2017-12-05T05:00:00.000Z,2017-12-05T05:00:00.000Z,CLOSED,MIAMI,25.750321,-80.417647,PHONE,30,5.0
3561770,3561771,BULKY TRASH UPDATE,Solid_Waste_Management,Solid Waste Management,10936 SW 139TH PL,Miami_Dade_County,Florida,33186.0,District 1,2017-11-30T05:00:00.000Z,2017-12-05T05:00:00.000Z,2017-12-05T05:00:00.000Z,CLOSED,MIAMI,25.665450,-80.422084,PHONE,30,5.0
3561784,3561785,BULKY TRASH UPDATE,Solid_Waste_Management,Solid Waste Management,2806 NW 51ST ST,Miami_Dade_County,Florida,33142.0,District 3,2017-11-30T05:00:00.000Z,2017-12-05T05:00:00.000Z,2017-12-05T05:00:00.000Z,CLOSED,MIAMI,25.820659,-80.242004,PHONE,30,5.0
3561872,3561873,BULKY TRASH UPDATE,Solid_Waste_Management,Solid Waste Management,1970 SW 57TH PL,Miami_Dade_County,Florida,33155.0,District 6,2017-11-30T05:00:00.000Z,2017-12-06T05:00:00.000Z,2017-12-06T05:00:00.000Z,CLOSED,MIAMI,25.752727,-80.289214,PHONE,30,6.0
3561896,3561897,BULKY TRASH UPDATE,Solid_Waste_Management,Solid Waste Management,5860 SW 156TH CT,Miami_Dade_County,Florida,33193.0,District 1,2017-11-30T05:00:00.000Z,2017-12-05T05:00:00.000Z,2017-12-05T05:00:00.000Z,CLOSED,MIAMI,25.710969,-80.446719,PHONE,30,5.0
3562054,3562055,BULKY TRASH UPDATE,Solid_Waste_Management,Solid Waste Management,12161 SW 135TH TER,Miami_Dade_County,Florida,33186.0,District 9,2017-11-30T05:00:00.000Z,2017-12-06T05:00:00.000Z,2017-12-06T05:00:00.000Z,CLOSED,MIAMI,25.642166,-80.390480,PHONE,30,6.0
3562476,3562477,BULKY TRASH UPDATE,Solid_Waste_Management,Solid Waste Management,10761 SW 131ST AVE,Miami_Dade_County,Florida,33186.0,District 8,2017-12-22T05:00:00.000Z,2017-12-26T05:00:00.000Z,2017-12-26T05:00:00.000Z,CLOSED,MIAMI,25.667294,-80.407093,PHONE,30,4.0
3562558,3562559,BULKY TRASH UPDATE,Solid_Waste_Management,Solid Waste Management,29265 SW 167TH AVE,Miami_Dade_County,Florida,33030.0,District 8,2017-12-22T05:00:00.000Z,2017-12-26T05:00:00.000Z,2017-12-26T05:00:00.000Z,CLOSED,MIAMI,25.494715,-80.460802,PHONE,30,4.0
3562566,3562567,BULKY TRASH UPDATE,Solid_Waste_Management,Solid Waste Management,5302 SW 162ND PL,Miami_Dade_County,Florida,33185.0,District 1,2017-12-22T05:00:00.000Z,2017-12-26T05:00:00.000Z,2017-12-26T05:00:00.000Z,CLOSED,MIAMI,25.715867,-80.457103,PHONE,30,4.0
3562760,3562761,BULKY TRASH UPDATE,Solid_Waste_Management,Solid Waste Management,4831 NW 170TH ST,Miami_Dade_County,Florida,33055.0,District 1,2017-12-22T05:00:00.000Z,2017-12-26T05:00:00.000Z,2017-12-26T05:00:00.000Z,CLOSED,MIAMI,25.928062,-80.279667,PHONE,30,4.0
3562922,3562923,BULKY TRASH UPDATE,Solid_Waste_Management,Solid Waste Management,1518 NW 99TH ST,Miami_Dade_County,Florida,33147.0,District 2,2017-12-22T05:00:00.000Z,2017-12-26T05:00:00.000Z,2017-12-26T05:00:00.000Z,CLOSED,MIAMI,25.864693,-80.224303,PHONE,30,4.0
3562958,3562959,BULKY TRASH UPDATE,Solid_Waste_Management,Solid Waste Management,15700 SW 109TH AVE,Miami_Dade_County,Florida,33157.0,District 9,2017-12-23T05:00:00.000Z,2018-01-02T05:00:00.000Z,2018-01-02T05:00:00.000Z,CLOSED,MIAMI,25.623101,-80.370783,PHONE,30,10.0
3562982,3562983,BULKY TRASH UPDATE,Solid_Waste_Management,Solid Waste Management,19405 SW 129TH AVE,Miami_Dade_County,Florida,33177.0,District 8,2017-12-22T05:00:00.000Z,2017-12-22T05:00:00.000Z,2017-12-22T05:00:00.000Z,CLOSED,MIAMI,25.585712,-80.400823,EMAIL,30,0.0
3563027,3563028,BULKY TRASH UPDATE,Solid_Waste_Management,Solid Waste Management,1008 NW 131ST AVE,Miami_Dade_County,Florida,33182.0,District 1,2017-12-23T05:00:00.000Z,2018-01-02T05:00:00.000Z,2017-01-02T05:00:00.000Z,CLOSED,MIAMI,25.780352,-80.407727,PHONE,30,-355.0
3563043,3563044,BULKY TRASH UPDATE,Solid_Waste_Management,Solid Waste Management,18539 SW 133RD AVE,Miami_Dade_County,Florida,33177.0,District 8,2017-12-23T05:00:00.000Z,2017-12-23T05:00:00.000Z,2017-01-02T05:00:00.000Z,CLOSED,MIAMI,25.595628,-80.406981,PHONE,30,-355.0
3563178,3563179,BULKY TRASH UPDATE,Solid_Waste_Management,Solid Waste Management,4050 SW 116TH AVE,Miami_Dade_County,Florida,33165.0,District 1,2017-12-22T05:00:00.000Z,2017-12-26T05:00:00.000Z,2017-12-26T05:00:00.000Z,CLOSED,MIAMI,25.730550,-80.382493,PHONE,30,4.0
3563311,3563312,BULKY TRASH UPDATE,Solid_Waste_Management,Solid Waste Management,4501 NW 31ST AVE,Miami_Dade_County,Florida,33142.0,District 3,2017-12-29T05:00:00.000Z,2018-01-02T05:00:00.000Z,2018-01-02T05:00:00.000Z,CLOSED,MIAMI,25.815915,-80.246346,PHONE,30,4.0
3563328,3563329,BULKY TRASH UPDATE,Solid_Waste_Management,Solid Waste Management,6560 SW 39TH ST,Miami_Dade_County,Florida,33155.0,District 6,2017-12-29T05:00:00.000Z,2018-01-02T05:00:00.000Z,2018-01-02T05:00:00.000Z,CLOSED,MIAMI,25.734722,-80.302148,PHONE,30,4.0
3563551,3563552,BULKY TRASH UPDATE,Solid_Waste_Management,Solid Waste Management,15233 SW 152ND AVE,Miami_Dade_County,Florida,33187.0,District 9,2017-12-29T05:00:00.000Z,2018-01-02T05:00:00.000Z,2018-01-02T05:00:00.000Z,CLOSED,MIAMI,25.624297,-80.438483,PHONE,30,4.0
3563894,3563895,BULKY TRASH UPDATE,Solid_Waste_Management,Solid Waste Management,939 NW 85TH ST,Miami_Dade_County,Florida,33150.0,District 2,2017-12-30T05:00:00.000Z,2018-01-02T05:00:00.000Z,2018-01-02T05:00:00.000Z,CLOSED,MIAMI,25.853730,-80.212853,PHONE,30,3.0

In [37]:
# load to db
total_avg_no_zero.to_sql(name='total_avg_0', con=engine, if_exists='replace', index=False)
city_avg_no_zero.to_sql(name='city_avg_0', con=engine, if_exists='replace', index=False)

In [38]:
merge_no_zero = pd.merge(city_avg_no_zero, total_avg_no_zero, on= 'issue_type')
#case_owner_x is from city df and case_owner_y is from total df the two are equal 
merge_no_zero

,city,case_owner_x,issue_type,mean,case_owner_y,total_mean
0,Bal_Harbour_Village,Citations_and_Tags,PET ACCOUNT UPDATE,1.571429,Citations_and_Tags,1.501179
1,CIty_of_Sunny_Isles_Beach,Citations_and_Tags,PET ACCOUNT UPDATE,1.209302,Citations_and_Tags,1.501179
2,City_of_Aventura,Citations_and_Tags,PET ACCOUNT UPDATE,2.218391,Citations_and_Tags,1.501179
3,City_of_Coral_Gables,Citations_and_Tags,PET ACCOUNT UPDATE,1.507143,Citations_and_Tags,1.501179
4,City_of_Doral,Citations_and_Tags,PET ACCOUNT UPDATE,1.490566,Citations_and_Tags,1.501179
5,City_of_Florida_City,Citations_and_Tags,PET ACCOUNT UPDATE,1.230769,Citations_and_Tags,1.501179
6,City_of_Hialeah,Citations_and_Tags,PET ACCOUNT UPDATE,1.406657,Citations_and_Tags,1.501179
7,City_of_Hialeah_Gardens,Citations_and_Tags,PET ACCOUNT UPDATE,2.426667,Citations_and_Tags,1.501179
8,City_of_Homestead,Citations_and_Tags,PET ACCOUNT UPDATE,1.376682,Citations_and_Tags,1.501179
9,City_of_Miami,Citations_and_Tags,PET ACCOUNT UPDATE,1.428918,Citations_and_Tags,1.501179
10,City_of_Miami_Beach,Citations_and_Tags,PET ACCOUNT UPDATE,1.451613,Citations_and_Tags,1.501179
11,City_of_Miami_Gardens,Citations_and_Tags,PET ACCOUNT UPDATE,1.662757,Citations_and_Tags,1.501179
12,City_of_Miami_Lakes,Citations_and_Tags,PET ACCOUNT UPDATE,1.313043,Citations_and_Tags,1.501179
13,City_of_Miami_Springs,Citations_and_Tags,PET ACCOUNT UPDATE,1.340909,Citations_and_Tags,1.501179
14,City_of_North_Miami,Citations_and_Tags,PET ACCOUNT UPDATE,1.314917,Citations_and_Tags,1.501179
15,City_of_North_Miami_Beach,Citations_and_Tags,PET ACCOUNT UPDATE,1.453237,Citations_and_Tags,1.501179
16,City_of_Opa-Locka,Citations_and_Tags,PET ACCOUNT UPDATE,1.403846,Citations_and_Tags,1.501179
17,City_of_Palmetto_Bay,Citations_and_Tags,PET ACCOUNT UPDATE,1.512605,Citations_and_Tags,1.501179
18,City_of_Pinecrest,Citations_and_Tags,PET ACCOUNT UPDATE,1.356164,Citations_and_Tags,1.501179
19,City_of_South_Miami,Citations_and_Tags,PET ACCOUNT UPDATE,1.511111,Citations_and_Tags,1.501179
20,City_of_Surfside,Citations_and_Tags,PET ACCOUNT UPDATE,1.111111,Citations_and_Tags,1.501179
21,City_of_Sweetwater,Citations_and_Tags,PET ACCOUNT UPDATE,1.647059,Citations_and_Tags,1.501179
22,City_of_West_Miami,Citations_and_Tags,PET ACCOUNT UPDATE,1.222222,Citations_and_Tags,1.501179
23,Miami_Dade_County,Citations_and_Tags,PET ACCOUNT UPDATE,1.503973,Citations_and_Tags,1.501179
24,Miami_Shores_Village,Citations_and_Tags,PET ACCOUNT UPDATE,1.166667,Citations_and_Tags,1.501179
25,North_Bay_Village,Citations_and_Tags,PET ACCOUNT UPDATE,1.555556,Citations_and_Tags,1.501179
26,Town_of_Bay_Harbor_Islands,Citations_and_Tags,PET ACCOUNT UPDATE,12.071429,Citations_and_Tags,1.501179
27,Town_of_Cutler_Bay,Citations_and_Tags,PET ACCOUNT UPDATE,1.433198,Citations_and_Tags,1.501179
28,Town_of_Golden_Beach,Citations_and_Tags,PET ACCOUNT UPDATE,1.000000,Citations_and_Tags,1.501179
29,Town_of_Medley,Citations_and_Tags,PET ACCOUNT UPDATE,1.500000,Citations_and_Tags,1.501179
...,...,...,...,...,...,...
1440,Miami_Dade_County,Regulatory_and_Economic_Resources,BUSINESS PREMISE MAINTENANCE,32.739726,Regulatory_and_Economic_Resources,32.739726
1441,Miami_Dade_County,Regulatory_and_Economic_Resources,COLLECTION BIN - UNAUTHORIZED,23.500000,Regulatory_and_Economic_Resources,23.500000
1442,Miami_Dade_County,Regulatory_and_Economic_Resources,FAILURE TO OBTAIN A CERTIFICATE OF USE,48.044877,Regulatory_and_Economic_Resources,48.154801
1443,Miami_Dade_County,Regulatory_and_Economic_Resources,FAILURE TO OBTAIN ZONING PERMIT,67.202550,Regulatory_and_Economic_Resources,67.034288
1444,Miami_Dade_County,Regulatory_and_Economic_Resources,"FENCE, HEDGE, TOWER, MAST - VIOLATIONS",36.236264,Regulatory_and_Economic_Resources,36.236264
1445,Miami_Dade_County,Regulatory_and_Economic_Resources,ILLEGAL EXCAVATION,68.800000,Regulatory_and_Economic_Resources,68.800000
1446,Miami_Dade_County,Regulatory_and_Economic_Resources,JUNKYARD REGULATIONS,33.200000,Regulatory_and_Economic_Resources,33.200000
1447,Miami_Dade_County,Regulatory_and_Economic_Resources,MINIMUM HOUSING BEE INFESTATION,25.478261,Regulatory_and_Economic_Resources,25.478261
1448,Miami_Dade_County,Regulatory_and_Economic_Resources,MINIMUM HOUSING CRACK HOUSE,2.666667,Regulatory_and_Economic_Resources,2.666667
1449,Miami_Dade_County,Regulatory_and_Economic_Resources,MINIMUM HOUSING MAINTENANCE,12.984375,Regulatory_and_Economic_Resources,12.917098
1450,Miami_Dade_County,Regulatory_and_Economic_Resources,MINIMUM HOUSING OVA (OPEN/VACANT/ABANDONED),23.421308,Regulatory_and_Economic_Resources,23.512077
1451,Miami_Dade_County,Regulatory_and_Economic_Resources,MOBILE HOME - ILLEGAL USE,61.444444,Regulatory_and_Economic_Resources,61.421053
1452,Miami_Dade_County,Regulatory_and_Economic_Resources,OUTSIDE BUSINESS USES - UNPERMITTED,52.828947,Regulatory_and_Economic_Resources,52.662338
1453,Miami_Dade_County,Regulatory_and_Economic_Resources,OUTSIDE OVERHEIGHT STACKING,125.000000,Regulatory_and_Economic_Resources,125.000000
1454,Miami_Dade_County,Regulatory_and_Economic_Resources,PARKING PREMISES VIOLATIONS,69.758242,Regulatory_and_Economic_Resources,69.758242
1455,Miami_Dade_County,Regulatory_and_Economic_Resources,POOL FENCE BARRIER,40.720812,Regulatory_and_Economic_Resources,40.686869
1456,Miami_Dade_County,Regulatory_and_Economic_Resources,PORTABLE ON-DEMAND STORAGE UNITS (PODs),20.849462,Regulatory_and_Economic_Resources,20.849462
1457,Miami_Dade_County,Regulatory_and_Economic_Resources,PREMISE LITTER VIOLATION,24.666667,Regulatory_and_Economic_Resources,24.666667
1458,Miami_Dade_County,Regulatory_and_Economic_Resources,RECREATIONAL VEHICLE / CAMPING EQUIPMENT STORAGE,25.078431,Regulatory_and_Economic_Resources,24.941748
1459,Miami_Dade_County,Regulatory_and_Economic_Resources,RESOLUTION VIOLATIONS,64.090909,Regulatory_and_Economic_Resources,64.090909
1460,Miami_Dade_County,Regulatory_and_Economic_Resources,RIGHT OF WAY NEWSRACKS,92.000000,Regulatory_and_Economic_Resources,92.000000
1461,Miami_Dade_County,Regulatory_and_Economic_Resources,RIGHT OF WAY - MAINTENANCE,20.411917,Regulatory_and_Economic_Resources,20.444588
1462,Miami_Dade_County,Regulatory_and_Economic_Resources,SETBACK VIOLATIONS,85.065268,Regulatory_and_Economic_Resources,85.376443
1463,Miami_Dade_County,Regulatory_and_Economic_Resources,SIGN - VIOLATION ON PRIVATE PROPERTY,25.265918,Regulatory_and_Economic_Resources,25.203636
1464,Miami_Dade_County,Regulatory_and_Economic_Resources,STRUCTURE MAINTENANCE - UPKEEP,61.900000,Regulatory_and_Economic_Resources,61.904550
1465,Miami_Dade_County,Regulatory_and_Economic_Resources,UNAUTHORIZED USE - INDUSTRIAL,59.704762,Regulatory_and_Economic_Resources,59.669811
1466,Miami_Dade_County,Regulatory_and_Economic_Resources,UNSECURED POOLS,23.871795,Regulatory_and_Economic_Resources,23.871795
1467,Miami_Dade_County,Regulatory_and_Economic_Resources,UNUSUAL USE OF PROPERTY,34.861357,Regulatory_and_Economic_Resources,34.817647
1468,Miami_Dade_County,Regulatory_and_Economic_Resources,VEHICLE ADVERTISING VIOLATION,11.436508,Regulatory_and_Economic_Resources,11.427445
1469,Miami_Dade_County,Regulatory_and_Economic_Resources,VENDORS - ILLEGAL,30.985714,Regulatory_and_Economic_Resources,30.985714

In [39]:
merge_no_zero['efficiency'] = (merge_no_zero['total_mean'] / merge_no_zero['mean']) * 100

In [40]:
#preview
merge_no_zero.head()

,city,case_owner_x,issue_type,mean,case_owner_y,total_mean,efficiency
0,Bal_Harbour_Village,Citations_and_Tags,PET ACCOUNT UPDATE,1.571429,Citations_and_Tags,1.501179,95.529556
1,CIty_of_Sunny_Isles_Beach,Citations_and_Tags,PET ACCOUNT UPDATE,1.209302,Citations_and_Tags,1.501179,124.135934
2,City_of_Aventura,Citations_and_Tags,PET ACCOUNT UPDATE,2.218391,Citations_and_Tags,1.501179,67.669715
3,City_of_Coral_Gables,Citations_and_Tags,PET ACCOUNT UPDATE,1.507143,Citations_and_Tags,1.501179,99.604277
4,City_of_Doral,Citations_and_Tags,PET ACCOUNT UPDATE,1.490566,Citations_and_Tags,1.501179,100.711991

In [41]:
#find where mean equals total mean
merge_no_zero.loc[(merge_no_zero['mean'] == merge_no_zero['total_mean']) & (merge_no_zero['efficiency'] == 100)]

,city,case_owner_x,issue_type,mean,case_owner_y,total_mean,efficiency
982,City_of_Coral_Gables,Public_Works_traffic_Signals_And_Signs-15-60,TRAFFIC SIGNAL OBSTRUCTED,17.000000,Public_Works_traffic_Signals_And_Signs-15-60,17.000000,100.0
1363,City_of_Miami,Public_Works_Traffic_Engineering-10-60,PEDESTRIAN CROSSING LIGHT - NEW,477.000000,Public_Works_Traffic_Engineering-10-60,477.000000,100.0
1372,City_of_Miami,Public_Works_traffic_Signals_And_Signs-15-60,TRAFFIC SIGNAL POLE HOLE COVER LOOSE / MISSING...,5.000000,Public_Works_traffic_Signals_And_Signs-15-60,5.000000,100.0
1407,City_of_Opa-Locka,Public_Works_Traffic_Engineering-10-60,TRAFFIC SIGNAL OTHER - CHANGE EXISTING,17.000000,Public_Works_Traffic_Engineering-10-60,17.000000,100.0
1415,Miami_Dade_County,Public_Works_Construction-6-60,DAMAGE TO PRIVATE PROPERTY BY THE COUNTY,5.857143,Public_Works_Construction-6-60,5.857143,100.0
1416,Miami_Dade_County,Public_Works_Construction-6-60,DEBRIS RELATED TO CONSTRUCTION ON ROW,6.857143,Public_Works_Construction-6-60,6.857143,100.0
1417,Miami_Dade_County,Public_Works_Construction-6-60,DRIVEWAY WITHOUT A PERMIT COMPLAINT,83.000000,Public_Works_Construction-6-60,83.000000,100.0
1418,Miami_Dade_County,Public_Works_Construction-6-60,ILLEGAL CONSTRUCTION ON COUNTY RIGHT OF WAY,59.000000,Public_Works_Construction-6-60,59.000000,100.0
1419,Miami_Dade_County,Public_Works_Construction-6-60,NEW DEVELOPMENT/SUBDIVISION CONSTRUCTION COMPL...,14.000000,Public_Works_Construction-6-60,14.000000,100.0
1422,Miami_Dade_County,Public_Works_Right_Of_Way-4-60,( ADA ) SIDEWALK REPAIR,9.333333,Public_Works_Right_Of_Way-4-60,9.333333,100.0
1423,Miami_Dade_County,Public_Works_Road_And_Bridges-16-60,APPLIANCE / REFRIGERATOR WITH DOOR,0.500000,Public_Works_Road_And_Bridges-16-60,0.500000,100.0
1429,Miami_Dade_County,Public_Works_Road_And_Bridges-16-60,PEDESTRIAN RAMP ( NOT ADA RELATED ),3.000000,Public_Works_Road_And_Bridges-16-60,3.000000,100.0
1431,Miami_Dade_County,Public_Works_Road_And_Bridges-16-60,SIDEWALK UNDERMINED ( HOLE UNDERNEATH ),3.416667,Public_Works_Road_And_Bridges-16-60,3.416667,100.0
1432,Miami_Dade_County,Public_Works_Traffic_Engineering-10-60,SIGN NEW - NO PARKING / STOPPING / STANDING - ...,129.000000,Public_Works_Traffic_Engineering-10-60,129.000000,100.0
1435,Miami_Dade_County,Regulatory_and_Economic_Resources,ADDRESS HOUSE NUMBER NOT DISPLAY,31.244009,Regulatory_and_Economic_Resources,31.244009,100.0
1436,Miami_Dade_County,Regulatory_and_Economic_Resources,ALCOHOLIC BEVERAGES SALES - PROHIBITED ZONING USE,149.666667,Regulatory_and_Economic_Resources,149.666667,100.0
1440,Miami_Dade_County,Regulatory_and_Economic_Resources,BUSINESS PREMISE MAINTENANCE,32.739726,Regulatory_and_Economic_Resources,32.739726,100.0
1441,Miami_Dade_County,Regulatory_and_Economic_Resources,COLLECTION BIN - UNAUTHORIZED,23.500000,Regulatory_and_Economic_Resources,23.500000,100.0
1444,Miami_Dade_County,Regulatory_and_Economic_Resources,"FENCE, HEDGE, TOWER, MAST - VIOLATIONS",36.236264,Regulatory_and_Economic_Resources,36.236264,100.0
1445,Miami_Dade_County,Regulatory_and_Economic_Resources,ILLEGAL EXCAVATION,68.800000,Regulatory_and_Economic_Resources,68.800000,100.0
1446,Miami_Dade_County,Regulatory_and_Economic_Resources,JUNKYARD REGULATIONS,33.200000,Regulatory_and_Economic_Resources,33.200000,100.0
1447,Miami_Dade_County,Regulatory_and_Economic_Resources,MINIMUM HOUSING BEE INFESTATION,25.478261,Regulatory_and_Economic_Resources,25.478261,100.0
1448,Miami_Dade_County,Regulatory_and_Economic_Resources,MINIMUM HOUSING CRACK HOUSE,2.666667,Regulatory_and_Economic_Resources,2.666667,100.0
1453,Miami_Dade_County,Regulatory_and_Economic_Resources,OUTSIDE OVERHEIGHT STACKING,125.000000,Regulatory_and_Economic_Resources,125.000000,100.0
1454,Miami_Dade_County,Regulatory_and_Economic_Resources,PARKING PREMISES VIOLATIONS,69.758242,Regulatory_and_Economic_Resources,69.758242,100.0
1456,Miami_Dade_County,Regulatory_and_Economic_Resources,PORTABLE ON-DEMAND STORAGE UNITS (PODs),20.849462,Regulatory_and_Economic_Resources,20.849462,100.0
1457,Miami_Dade_County,Regulatory_and_Economic_Resources,PREMISE LITTER VIOLATION,24.666667,Regulatory_and_Economic_Resources,24.666667,100.0
1459,Miami_Dade_County,Regulatory_and_Economic_Resources,RESOLUTION VIOLATIONS,64.090909,Regulatory_and_Economic_Resources,64.090909,100.0
1460,Miami_Dade_County,Regulatory_and_Economic_Resources,RIGHT OF WAY NEWSRACKS,92.000000,Regulatory_and_Economic_Resources,92.000000,100.0
1466,Miami_Dade_County,Regulatory_and_Economic_Resources,UNSECURED POOLS,23.871795,Regulatory_and_Economic_Resources,23.871795,100.0
1469,Miami_Dade_County,Regulatory_and_Economic_Resources,VENDORS - ILLEGAL,30.985714,Regulatory_and_Economic_Resources,30.985714,100.0

In [42]:
#remove areas with mean equal to total mean b/c there is no standard to compare with
merge_no_zero_clean = merge_no_zero.loc[merge_no_zero['mean'] != merge_no_zero['total_mean']]
merge_no_zero_clean.head()
#merge_no_zero.loc[(merge_no_zero['case_owner_y'] == 'Citations_and_Tags') &(merge_no_zero['issue_type'] == 'FOUND PET')]

,city,case_owner_x,issue_type,mean,case_owner_y,total_mean,efficiency
0,Bal_Harbour_Village,Citations_and_Tags,PET ACCOUNT UPDATE,1.571429,Citations_and_Tags,1.501179,95.529556
1,CIty_of_Sunny_Isles_Beach,Citations_and_Tags,PET ACCOUNT UPDATE,1.209302,Citations_and_Tags,1.501179,124.135934
2,City_of_Aventura,Citations_and_Tags,PET ACCOUNT UPDATE,2.218391,Citations_and_Tags,1.501179,67.669715
3,City_of_Coral_Gables,Citations_and_Tags,PET ACCOUNT UPDATE,1.507143,Citations_and_Tags,1.501179,99.604277
4,City_of_Doral,Citations_and_Tags,PET ACCOUNT UPDATE,1.490566,Citations_and_Tags,1.501179,100.711991

In [43]:
#final df
merge_no_zero_final = merge_no_zero_clean[['city', 'case_owner_x', 'issue_type','mean', 'efficiency']]
merge_no_zero_final.head()

,city,case_owner_x,issue_type,mean,efficiency
0,Bal_Harbour_Village,Citations_and_Tags,PET ACCOUNT UPDATE,1.571429,95.529556
1,CIty_of_Sunny_Isles_Beach,Citations_and_Tags,PET ACCOUNT UPDATE,1.209302,124.135934
2,City_of_Aventura,Citations_and_Tags,PET ACCOUNT UPDATE,2.218391,67.669715
3,City_of_Coral_Gables,Citations_and_Tags,PET ACCOUNT UPDATE,1.507143,99.604277
4,City_of_Doral,Citations_and_Tags,PET ACCOUNT UPDATE,1.490566,100.711991

In [44]:
#rename final df column
merge_no_zero_final_rename = merge_no_zero_final.rename(columns={'case_owner_x': 'case_owner'})
merge_no_zero_final_rename.head()

,city,case_owner,issue_type,mean,efficiency
0,Bal_Harbour_Village,Citations_and_Tags,PET ACCOUNT UPDATE,1.571429,95.529556
1,CIty_of_Sunny_Isles_Beach,Citations_and_Tags,PET ACCOUNT UPDATE,1.209302,124.135934
2,City_of_Aventura,Citations_and_Tags,PET ACCOUNT UPDATE,2.218391,67.669715
3,City_of_Coral_Gables,Citations_and_Tags,PET ACCOUNT UPDATE,1.507143,99.604277
4,City_of_Doral,Citations_and_Tags,PET ACCOUNT UPDATE,1.490566,100.711991

In [45]:
#check why hialeah disappeared
merge_no_zero_final_rename.loc[merge_no_zero_final_rename['issue_type']=='SEAWALL / HEADWALL COLLAPSING']

,city,case_owner,issue_type,mean,efficiency
1282,City_of_Hialeah,Public_Works_Road_And_Bridges-16-60,SEAWALL / HEADWALL COLLAPSING,245.00,57.823129
1283,Miami_Dade_County,Public_Works_Road_And_Bridges-16-60,SEAWALL / HEADWALL COLLAPSING,128.75,110.032362

In [46]:
#issue_type with value count of 1 have city listed as None, these were dropped hence only one occurace,
# mean and efficiency unaffected since drop happened after calculations
merge_no_zero_final_rename['issue_type'].value_counts()

MOSQUITO INSPECTION REQUEST                                                         36
PET ACCOUNT UPDATE                                                                  34
MOSQUITOES CAUSING A BITING NUISANCE                                                33
ANIMAL BITE TO A PERSON                                                             31
ANIMAL CRUELTY INVESTIGATION                                                        29
STRAY / DOG-AT-LARGE                                                                29
DEAD ANIMAL PICKUP MD                                                               29
LOST PET                                                                            28
ANIMAL SERVICES DOG TAG CHECK                                                       27
POTHOLE                                                                             26
TRAFFIC SIGNAL RED DISPLAY TOO LONG OR GREEN TOO SHORT                              26
STRAY DOG PICK UP - MD                                                              25
TRAFFIC SIGNAL COMPLETELY OUT                                                       25
DANGEROUS DOG INVESTIGATION                                                         25
ILLEGAL DUMPING - WM                                                                24
TRAFFIC SIGN  CONTROL SIGNS  DOWN DAMAGED  MISSING                                  24
PIT BULL INVESTIGATION                                                              24
TRAFFIC SIGNAL OUT OF SYNC WITH OTHER TRAFFIC SIGNALS (SAME DIRECTION OF TRAVEL)    23
ANIMAL CRUELTY FOLLOW-UP                                                            23
TRAFFIC SIGN DOWN DAMAGED FADED MISSING (OTHER THAN CONTROL SIGN)                   23
TETHERED DOG                                                                        22
TRAFFIC SIGNAL MALFUNCTION FLASHING YELLOW AND / OR RED                             22
TRAFFIC SIGNAL PED LIGHT OR BUTTON INOPERATIVE                                      21
TRAFFIC SIGNAL BULB BURNED OUT                                                      21
RECYCLING BLUE CART ISSUES                                                          20
ASU POLICE ASSISTANCE                                                               20
TREE TRIMMING (RAAM)                                                                19
SIDEWALK BROKEN / RAISED                                                            19
RECYCLING COMPLAINT                                                                 18
VISUAL OBSTRUCTION SAFETY ISSUE (RAAM)                                              18
                                                                                    ..
SEAWALL / HEADWALL COLLAPSING                                                        2
SIGN NEW - 4-WAY STOP                                                                2
DRAIN - OBJECT REMOVAL                                                               2
( ADA ) NEW SIDEWALK                                                                 2
TRAFFIC STUDY - MISCELLANEOUS - IN PUBLIC ROW                                        2
UNAUTHORIZED USE - RESIDENTIAL / BUSINESS                                            2
SIGNS ON THE ROW                                                                     2
MINIMUM HOUSING OVA (OPEN/VACANT/ABANDONED)                                          1
FAILURE TO OBTAIN ZONING PERMIT                                                      1
BOAT STORAGE                                                                         1
DRAIN TOPS CLEANED                                                                   1
UNUSUAL USE OF PROPERTY                                                              1
MINIMUM HOUSING MAINTENANCE                                                          1
DEBRIS ON ROADWAY DRIVING SURFACE                                                    1
SIDEWALK GRINDING                                                                    1
SETBACK VIOLATIONS                                                                   1
ALL OTHER ZONING VIOLATIONS                                                          1
VEHICLE ADVERTISING VIOLATION                                                        1
UNAUTHORIZED USE - INDUSTRIAL                                                        1
FAILURE TO OBTAIN A CERTIFICATE OF USE                                               1
ANIMAL SERVICES DOG TAG                                                              1
POOL FENCE BARRIER                                                                   1
AUTO REPAIRS - RESIDENTIAL                                                           1
GUARDRAIL / HANDRAIL NEW INSTALLATION                                                1
SIGN - VIOLATION ON PRIVATE PROPERTY                                                 1
RECREATIONAL VEHICLE / CAMPING EQUIPMENT STORAGE                                     1
OUTSIDE BUSINESS USES - UNPERMITTED                                                  1
RIGHT OF WAY - MAINTENANCE                                                           1
MOBILE HOME - ILLEGAL USE                                                            1
STRUCTURE MAINTENANCE - UPKEEP                                                       1
Name: issue_type, Length: 156, dtype: int64

In [47]:
#load table
merge_no_zero_final_rename.to_sql(name='city_efficiency', con=engine, if_exists='replace', index=False)

In [48]:
#check table
efficiency_df = pd.read_sql_query('select * from city_efficiency', con=engine)
efficiency_df.head()

,city,case_owner,issue_type,mean,efficiency
0,Bal_Harbour_Village,Citations_and_Tags,PET ACCOUNT UPDATE,1.571429,95.529556
1,CIty_of_Sunny_Isles_Beach,Citations_and_Tags,PET ACCOUNT UPDATE,1.209302,124.135934
2,City_of_Aventura,Citations_and_Tags,PET ACCOUNT UPDATE,2.218391,67.669715
3,City_of_Coral_Gables,Citations_and_Tags,PET ACCOUNT UPDATE,1.507143,99.604277
4,City_of_Doral,Citations_and_Tags,PET ACCOUNT UPDATE,1.490566,100.711991

In [49]:
#Get zip code efficiency
zip_service =service_closed[['issue_type', 'case_owner','city','location_city','zip_code','actual_completed_days']]
zip_service.head()

,issue_type,case_owner,city,location_city,zip_code,actual_completed_days
0,BULKY TRASH REQUEST,Solid_Waste_Management,Miami_Dade_County,MIAMI,33165.0,9.0
1,RECYCLING BLUE CART ISSUES,Solid_Waste_Management,Miami_Dade_County,MIAMI,33196.0,7.0
2,GREEN WASTE CART REQUEST,Solid_Waste_Management,Miami_Dade_County,MIAMI,33196.0,7.0
3,GREEN WASTE CART REQUEST,Solid_Waste_Management,Miami_Dade_County,MIAMI,33182.0,8.0
4,GARBAGE COMPLAINT,Solid_Waste_Management,Miami_Dade_County,MIAMI,33142.0,2.0

In [50]:
zip_group = zip_service.groupby(['zip_code', 'case_owner','issue_type'])
#df_calc = city_group.describe()
#df_calc.head()
#df_reset = df_calc.reset_index()
zip_df = zip_group.describe()

In [51]:
zip_df.head()

                                                                                      actual_completed_days  \
                                                                                                      count
zip_code case_owner                issue_type
3301.0   Enforcement_Section-3-36  INJURED ANIMAL                                                      11.0
33010.0  Citations_and_Tags        FOUND PET                                                           11.0
                                   LOST PET                                                           176.0
                                   PET ACCOUNT UPDATE                                                1540.0
         Communications_Department 311 ACTIVATION - FPL (POWER LINE DOWN/POWER OUT...                 649.0

                                                                                                 \
                                                                                           mean
zip_code case_owner                issue_type
3301.0   Enforcement_Section-3-36  INJURED ANIMAL                                      0.000000
33010.0  Citations_and_Tags        FOUND PET                                           2.000000
                                   LOST PET                                            3.750000
                                   PET ACCOUNT UPDATE                                  1.428571
         Communications_Department 311 ACTIVATION - FPL (POWER LINE DOWN/POWER OUT...  0.033898

                                                                                                 \
                                                                                            std
zip_code case_owner                issue_type
3301.0   Enforcement_Section-3-36  INJURED ANIMAL                                      0.000000
33010.0  Citations_and_Tags        FOUND PET                                           0.000000
                                   LOST PET                                            2.082581
                                   PET ACCOUNT UPDATE                                  0.838151
         Communications_Department 311 ACTIVATION - FPL (POWER LINE DOWN/POWER OUT...  0.181107

                                                                                            \
                                                                                       min
zip_code case_owner                issue_type
3301.0   Enforcement_Section-3-36  INJURED ANIMAL                                      0.0
33010.0  Citations_and_Tags        FOUND PET                                           2.0
                                   LOST PET                                            1.0
                                   PET ACCOUNT UPDATE                                  1.0
         Communications_Department 311 ACTIVATION - FPL (POWER LINE DOWN/POWER OUT...  0.0

                                                                                             \
                                                                                        25%
zip_code case_owner                issue_type
3301.0   Enforcement_Section-3-36  INJURED ANIMAL                                      0.00
33010.0  Citations_and_Tags        FOUND PET                                           2.00
                                   LOST PET                                            2.75
                                   PET ACCOUNT UPDATE                                  1.00
         Communications_Department 311 ACTIVATION - FPL (POWER LINE DOWN/POWER OUT...  0.00

                                                                                            \
                                                                                       50%
zip_code case_owner                issue_type
3301.0   Enforcement_Section-3-36  INJURED ANIMAL                                      0.0
33010.0  Citations_and_Tags        FOUND PET                                           2.0
                                   LOST PET                                            3.0
                                   PET ACCOUNT UPDATE                                  1.0
         Communications_Department 311 ACTIVATION - FPL (POWER LINE DOWN/POWER OUT...  0.0

                                                                                            \
                                                                                       75%
zip_code case_owner                issue_type
3301.0   Enforcement_Section-3-36  INJURED ANIMAL                                      0.0
33010.0  Citations_and_Tags        FOUND PET                                           2.0
                                   LOST PET                                            4.5
                                   PET ACCOUNT UPDATE                                  1.0
         Communications_Department 311 ACTIVATION - FPL (POWER LINE DOWN/POWER OUT...  0.0


                                                                                       max
zip_code case_owner                issue_type
3301.0   Enforcement_Section-3-36  INJURED ANIMAL                                      0.0
33010.0  Citations_and_Tags        FOUND PET                                           2.0
                                   LOST PET                                            8.0
                                   PET ACCOUNT UPDATE                                  4.0
         Communications_Department 311 ACTIVATION - FPL (POWER LINE DOWN/POWER OUT...  1.0

In [52]:
zip_reset = zip_df.reset_index()

In [53]:
zip_reset.head()

  zip_code                 case_owner  \

0   3301.0   Enforcement_Section-3-36
1  33010.0         Citations_and_Tags
2  33010.0         Citations_and_Tags
3  33010.0         Citations_and_Tags
4  33010.0  Communications_Department

                                          issue_type actual_completed_days  \
                                                                     count
0                                     INJURED ANIMAL                  11.0
1                                          FOUND PET                  11.0
2                                           LOST PET                 176.0
3                                 PET ACCOUNT UPDATE                1540.0
4  311 ACTIVATION - FPL (POWER LINE DOWN/POWER OU...                 649.0


       mean       std  min   25%  50%  75%  max
0  0.000000  0.000000  0.0  0.00  0.0  0.0  0.0
1  2.000000  0.000000  2.0  2.00  2.0  2.0  2.0
2  3.750000  2.082581  1.0  2.75  3.0  4.5  8.0
3  1.428571  0.838151  1.0  1.00  1.0  1.0  4.0
4  0.033898  0.181107  0.0  0.00  0.0  0.0  1.0

In [54]:
#Drop multilevel index 
zip_reset.columns = zip_reset.columns.droplevel()
#new_index
#df_reset.columns.droplevel(1)
zip_reset.head()

,,,,count,mean,std,min,25%,50%,75%,max
0,3301.0,Enforcement_Section-3-36,INJURED ANIMAL,11.0,0.000000,0.000000,0.0,0.00,0.0,0.0,0.0
1,33010.0,Citations_and_Tags,FOUND PET,11.0,2.000000,0.000000,2.0,2.00,2.0,2.0,2.0
2,33010.0,Citations_and_Tags,LOST PET,176.0,3.750000,2.082581,1.0,2.75,3.0,4.5,8.0
3,33010.0,Citations_and_Tags,PET ACCOUNT UPDATE,1540.0,1.428571,0.838151,1.0,1.00,1.0,1.0,4.0
4,33010.0,Communications_Department,311 ACTIVATION - FPL (POWER LINE DOWN/POWER OU...,649.0,0.033898,0.181107,0.0,0.00,0.0,0.0,1.0

In [55]:
#rename columns
zip_reset.columns = ['zip_code', 'case_owner', 'issue_type', 'count', 'mean', 'std', 'min', '25%', '50%', '75%', 'max']
zip_reset.head()

,zip_code,case_owner,issue_type,count,mean,std,min,25%,50%,75%,max
0,3301.0,Enforcement_Section-3-36,INJURED ANIMAL,11.0,0.000000,0.000000,0.0,0.00,0.0,0.0,0.0
1,33010.0,Citations_and_Tags,FOUND PET,11.0,2.000000,0.000000,2.0,2.00,2.0,2.0,2.0
2,33010.0,Citations_and_Tags,LOST PET,176.0,3.750000,2.082581,1.0,2.75,3.0,4.5,8.0
3,33010.0,Citations_and_Tags,PET ACCOUNT UPDATE,1540.0,1.428571,0.838151,1.0,1.00,1.0,1.0,4.0
4,33010.0,Communications_Department,311 ACTIVATION - FPL (POWER LINE DOWN/POWER OU...,649.0,0.033898,0.181107,0.0,0.00,0.0,0.0,1.0

In [56]:
zip_drop = zip_reset[['zip_code', 'case_owner', 'issue_type', 'mean']]
#zip_code_df = zip_drop.dropna()
#zip_drop.isna().any()
zip_drop.head()

,zip_code,case_owner,issue_type,mean
0,3301.0,Enforcement_Section-3-36,INJURED ANIMAL,0.000000
1,33010.0,Citations_and_Tags,FOUND PET,2.000000
2,33010.0,Citations_and_Tags,LOST PET,3.750000
3,33010.0,Citations_and_Tags,PET ACCOUNT UPDATE,1.428571
4,33010.0,Communications_Department,311 ACTIVATION - FPL (POWER LINE DOWN/POWER OU...,0.033898

In [57]:
zip_avg_no_zero = zip_drop.loc[zip_drop['mean'] != 0]
zip_avg_no_zero.head()

,zip_code,case_owner,issue_type,mean
1,33010.0,Citations_and_Tags,FOUND PET,2.000000
2,33010.0,Citations_and_Tags,LOST PET,3.750000
3,33010.0,Citations_and_Tags,PET ACCOUNT UPDATE,1.428571
4,33010.0,Communications_Department,311 ACTIVATION - FPL (POWER LINE DOWN/POWER OU...,0.033898
5,33010.0,Enforcement_Section-3-36,ANIMAL BITE TO A PERSON,4.500000

In [58]:
#load
zip_avg_no_zero.to_sql(name='zip_avg_0', con=engine, if_exists='replace', index=False)

In [59]:
zip_merge_no_zero = pd.merge(zip_avg_no_zero, total_avg_no_zero, on= 'issue_type')
#case_owner_x is from city df and case_owner_y is from total df the two are equal 
zip_merge_no_zero.head()

,zip_code,case_owner_x,issue_type,mean,case_owner_y,total_mean
0,33010.0,Citations_and_Tags,FOUND PET,2.000000,Citations_and_Tags,10.347826
1,33012.0,Citations_and_Tags,FOUND PET,43.000000,Citations_and_Tags,10.347826
2,33016.0,Citations_and_Tags,FOUND PET,3.000000,Citations_and_Tags,10.347826
3,33030.0,Citations_and_Tags,FOUND PET,1.000000,Citations_and_Tags,10.347826
4,33033.0,Citations_and_Tags,FOUND PET,1.666667,Citations_and_Tags,10.347826

In [60]:
#Calc efficiency
zip_merge_no_zero['efficiency'] = (zip_merge_no_zero['total_mean'] / zip_merge_no_zero['mean']) * 100

In [61]:
zip_merge_no_zero.head()

,zip_code,case_owner_x,issue_type,mean,case_owner_y,total_mean,efficiency
0,33010.0,Citations_and_Tags,FOUND PET,2.000000,Citations_and_Tags,10.347826,517.391304
1,33012.0,Citations_and_Tags,FOUND PET,43.000000,Citations_and_Tags,10.347826,24.064712
2,33016.0,Citations_and_Tags,FOUND PET,3.000000,Citations_and_Tags,10.347826,344.927536
3,33030.0,Citations_and_Tags,FOUND PET,1.000000,Citations_and_Tags,10.347826,1034.782609
4,33033.0,Citations_and_Tags,FOUND PET,1.666667,Citations_and_Tags,10.347826,620.869565

In [62]:
#remove areas with mean equal to total mean b/c there is no standard to compare with
zip_merge_no_zero_clean = zip_merge_no_zero.loc[zip_merge_no_zero['mean'] != zip_merge_no_zero['total_mean']]
zip_merge_no_zero_clean.head()

,zip_code,case_owner_x,issue_type,mean,case_owner_y,total_mean,efficiency
0,33010.0,Citations_and_Tags,FOUND PET,2.000000,Citations_and_Tags,10.347826,517.391304
1,33012.0,Citations_and_Tags,FOUND PET,43.000000,Citations_and_Tags,10.347826,24.064712
2,33016.0,Citations_and_Tags,FOUND PET,3.000000,Citations_and_Tags,10.347826,344.927536
3,33030.0,Citations_and_Tags,FOUND PET,1.000000,Citations_and_Tags,10.347826,1034.782609
4,33033.0,Citations_and_Tags,FOUND PET,1.666667,Citations_and_Tags,10.347826,620.869565

In [63]:
#final df
zip_merge_no_zero_final = zip_merge_no_zero_clean[['zip_code', 'case_owner_x', 'issue_type','mean', 'efficiency']]
zip_merge_no_zero_final.head()

   zip_code        case_owner_x issue_type       mean   efficiency
0   33010.0  Citations_and_Tags  FOUND PET   2.000000   517.391304
1   33012.0  Citations_and_Tags  FOUND PET  43.000000    24.064712
2   33016.0  Citations_and_Tags  FOUND PET   3.000000   344.927536
3   33030.0  Citations_and_Tags  FOUND PET   1.000000  1034.782609
4   33033.0  Citations_and_Tags  FOUND PET   1.666667   620.869565

In [64]:
#rename final df column
zip_merge_no_zero_final_rename = zip_merge_no_zero_final.rename(columns={'case_owner_x': 'case_owner'})
zip_merge_no_zero_final_rename.head()

   zip_code          case_owner issue_type       mean   efficiency
0   33010.0  Citations_and_Tags  FOUND PET   2.000000   517.391304
1   33012.0  Citations_and_Tags  FOUND PET  43.000000    24.064712
2   33016.0  Citations_and_Tags  FOUND PET   3.000000   344.927536
3   33030.0  Citations_and_Tags  FOUND PET   1.000000  1034.782609
4   33033.0  Citations_and_Tags  FOUND PET   1.666667   620.869565

In [65]:
#load table
zip_merge_no_zero_final_rename.to_sql(name='zip_efficiency', con=engine, if_exists='replace', index=False)

In [66]:
#check table
zip_efficiency_df = pd.read_sql_query('select * from zip_efficiency', con=engine)
zip_efficiency_df.head()

   zip_code          case_owner issue_type       mean   efficiency
0   33010.0  Citations_and_Tags  FOUND PET   2.000000   517.391304
1   33012.0  Citations_and_Tags  FOUND PET  43.000000    24.064712
2   33016.0  Citations_and_Tags  FOUND PET   3.000000   344.927536
3   33030.0  Citations_and_Tags  FOUND PET   1.000000  1034.782609
4   33033.0  Citations_and_Tags  FOUND PET   1.666667   620.869565